"""What the report says about an artifact that exists and was not handed over.

A run that fails reaches the author as a message rather than as a record, so D7's
"a withheld artifact is named" has to be satisfied by the reporting layer for those
outcomes. A sweep found it was not pinned: emptying the line's producer left all 421
tests green, because every test that asserts on it goes through the returning path
instead.

Pinning the producer was not enough either -- with a test calling `_kept` directly,
deleting every *call* to it still left 426 green. So the last two here drive `main`,
which is where org contract section 5 puts the surface anyway.
"""

from __future__ import annotations

from pathlib import Path

import pytest

import slicelab.cli as cli
from slicelab.cli import _kept
from slicelab.plan import PlanError
from slicelab.resolve import ResolveError, ResolveIncomplete
from slicelab.slicing import _WITHHELD


def test_a_fault_carrying_a_withheld_artifact_is_reported_with_its_path() -> None:
    """The path is rendered the way the platform spells it -- a literal with forward
    slashes was red on the Windows leg and green everywhere else."""
    kept = Path("/scratch/slicelab-slice-abcd/artifact")
    fault = ResolveError("cannot write the artifact")
    setattr(fault, _WITHHELD, kept)

    assert _kept(fault) == [f"the artifact it did produce was kept at {kept}"]


def test_a_fault_with_no_withheld_artifact_says_nothing() -> None:
    """The control, and the thing that matters more: [V4] and [V15] produce no
    artifact, and a report naming a path with no file at it is worse than silence."""
    assert _kept(ResolveError("no usable prusaslicer on this machine")) == []


def test_an_unexpected_fault_is_reported_as_error_and_names_what_it_kept(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    """Exit 4 with the outcome word, not CPython's exit 1 with a traceback.

    1 is `refused`, which asserts slicelab read the intent and found it wanting. An
    `OSError` out of the container sniff says nothing of the kind -- and it arrives
    after the engine has produced an artifact slicelab is now keeping, so a report
    that is a traceback is also a scratch directory nobody was told about.
    """
    kept = tmp_path / "scratch" / "artifact"
    kept.parent.mkdir()
    kept.write_bytes(b"; generated by a slicer\n")

    def explode(intent_path: Path):
        fault = OSError("device is busy")
        setattr(fault, _WITHHELD, kept)
        raise fault

    monkeypatch.setattr(cli, "slice_intent", explode)
    intent = tmp_path / "slice.toml"
    intent.write_text("[geometry]\n", encoding="utf-8")

    code = cli.main(["slice", str(intent)])

    report = capsys.readouterr().err
    assert code == 4, report
    assert report.startswith("error"), report
    assert "OSError: device is busy" in report, report
    # The traceback follows the outcome word rather than replacing it. Without it an
    # `AssertionError` with an empty message is one line nobody can act on.
    assert "Traceback (most recent call last)" in report, report
    assert report.index("error") < report.index("Traceback"), report
    assert f"kept at {kept}" in report, report


def test_a_refusal_reports_no_kept_artifact_when_there_is_none(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The control, through the same surface. [V4] and [V15] produce no artifact, and
    a report naming a path with no file at it is worse than one naming nothing."""
    intent = tmp_path / "slice.toml"
    intent.write_text("[prusaslicer.base]\n", encoding="utf-8")

    code = cli.main(["slice", str(intent)])

    report = capsys.readouterr().err
    assert code in (1, 4), report
    assert "kept at" not in report, report


@pytest.mark.parametrize(
    ("fault", "outcome", "code"),
    [
        (ResolveError("cannot write the artifact: cannot write /out/part.gcode"), "error", 4),
        (ResolveIncomplete("prusaslicer exited 1 having written an artifact"), "incomplete", 2),
        (PlanError("slice.toml sends the artifact to the intent itself"), "refused", 1),
    ],
    ids=["error", "incomplete", "refused"],
)
def test_every_outcome_that_can_withhold_an_artifact_names_it(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
    fault: Exception,
    outcome: str,
    code: int,
) -> None:
    """One call site per outcome, and each one is its own chance to forget.

    Deleting the call from the `error` branch alone left all 429 tests green: the
    only end-to-end cover was on the branch for faults nobody anticipated, which is
    the one least likely to carry an artifact. `error` is the one that does -- it is
    where a failed promotion lands.
    """
    kept = tmp_path / "scratch" / "artifact"
    kept.parent.mkdir()
    kept.write_bytes(b"; generated by a slicer\n")
    setattr(fault, _WITHHELD, kept)

    def explode(intent_path: Path):
        raise fault

    monkeypatch.setattr(cli, "slice_intent", explode)
    intent = tmp_path / "slice.toml"
    intent.write_text("[geometry]\n", encoding="utf-8")

    assert cli.main(["slice", str(intent)]) == code
    report = capsys.readouterr().err
    assert report.startswith(outcome), report
    assert f"kept at {kept}" in report, report
