"""The option-to-key map, and the three ways a probe can measure silence.

``notes/critique.md`` G2 is the reason the map is probed rather than derived, and
the reason it must not be derived is reproduced here as an engine test: on
PrusaSlicer 2.9.6 ``--after-layer-gcode`` writes ``layer_gcode``, and a
dash-to-underscore readback calls that a perfectly applied key ``absent``.

Most of this file needs no engine. The classification rules are where the probe
can silently become wrong -- an engine that writes no artifact at exit 0 would
otherwise read as an option that moved every key at once -- so each of them is
driven against a stand-in and has a red state on every runner, including the ones
with no slicer installed.
"""

from __future__ import annotations

import ast
import json
import os
import re
from collections.abc import Callable, Mapping
from dataclasses import replace
from pathlib import Path

import pytest

from slicelab.adapters import ORCASLICER, PRUSASLICER, EngineSpec
from slicelab.adapters.orcaslicer import _options_from_settings_keys, _read_settings_json
from slicelab.adapters.prusaslicer import _options_from_help_fff, _read_ini
from slicelab.engine.characterise import (
    Characterisation,
    CharacterisationError,
    MapEntry,
    ProbeOutcome,
    Tracking,
    _cache_root,
    _confirm_the_inert,
    _probe_one,
    _read_cache,
    _safe,
    _unmapped,
    _write_cache,
    cache_path_for,
    characterise,
    load_name_map,
)
from slicelab.engine.discover import Discovery, ExitFidelity, LaunchForm, LaunchKind, argv_for
from slicelab.engine.launch import Completed, run
from tests.test_names_confined import undeclared_terms

PACKAGE = Path(__file__).resolve().parent.parent / "slicelab"

# -- the adapters' halves: enumerating options, and reading a readback ---------

#: The two line shapes ``--help-fff`` actually uses, reduced to their skeletons.
#: The second is D28's alias line -- the one a leading-option scan misses, and the
#: one that produced G2's false ``absent``.
HELP_SAMPLE = """PrusaSlicer-2.9.6 based on Slic3r

Actions:
 --export-sla, --sla Slice the model and export SLA printing layers as PNG.
 --help, -h          Show this help.

Options:
 --after-layer-gcode ABCD, --layer-gcode ABCD
                     Custom G-code per layer.
 --bed-shape         (default: 0x0,200x0,200x200,0x200)
 --perimeters N      How many perimeters.
Note: a prose line that mentions --perimeters must not become an option.
"""


def test_the_help_parser_reads_past_the_first_name_on_a_line() -> None:
    """Aliases are the population the collision search has to be exhaustive over."""
    found = _options_from_help_fff(HELP_SAMPLE, {})
    assert found == (
        "export-sla",
        "sla",
        "help",
        "after-layer-gcode",
        "layer-gcode",
        "bed-shape",
        "perimeters",
    )


def test_the_help_parser_stops_at_the_description() -> None:
    """A description is not a spelling, whatever punctuation it contains.

    ``--export-sla, --sla Slice the model...`` puts the description on the same
    line as the second spelling, so reading every comma-separated group would
    harvest sentences as option names.
    """
    assert "slice" not in _options_from_help_fff(HELP_SAMPLE, {})
    assert not any(" " in name for name in _options_from_help_fff(HELP_SAMPLE, {}))


def test_the_help_parser_ignores_prose_that_names_an_option() -> None:
    """Only a line that *starts* with an option is an option line."""
    assert _options_from_help_fff("Config keys such as --fill-pattern=stars.\n", {}) == ()


def test_the_ini_reader_takes_values_verbatim() -> None:
    """A resolved G-code block has to survive the round trip unaltered.

    The readback compares requested against resolved for equality, so a reader
    that strips or normalises is deciding a key was applied on evidence it
    changed itself.
    """
    parsed = _read_ini(
        "# generated by PrusaSlicer\n"
        "[print:x]\n"
        "layer_gcode = ;LAYER {layer_num}\\nM117 hi \n"
        "perimeters = 3\n"
        "notes = \n"
    )
    assert parsed == {
        "layer_gcode": ";LAYER {layer_num}\\nM117 hi ",
        "perimeters": "3",
        "notes": "",
    }


def test_the_settings_reader_keeps_a_list_distinguishable_from_a_string() -> None:
    """``["1", "0"]`` and ``"1,0"`` are different states and must stay different."""
    parsed = _read_settings_json('{"a": "2", "b": ["1", "0"], "c": ["1,0"]}')
    assert parsed["a"] == "2"
    assert parsed["b"] != parsed["c"]


def test_orca_candidates_come_from_the_keys_because_orca_lists_no_options() -> None:
    assert _options_from_settings_keys("", {"wall_loops": "2", "a_b_c": "1"}) == (
        "a-b-c",
        "wall-loops",
    )


# -- the driver's classification rules, against a stand-in engine --------------

FORM = LaunchForm(LaunchKind.PATH, ["/nonexistent/engine"], "a stand-in")
FOUND = Discovery(engine="stand-in", form=FORM, fidelity=ExitFidelity.ESTABLISHED, reason="test")
BASELINE: Mapping[str, str] = {"alpha": "1", "beta": "2", "gamma": "3"}

_PROBE = PRUSASLICER.option_probe
assert _PROBE is not None
PAIRS = _PROBE.sentinels
#: The first pair tried, and the second. Read off the adapter rather than
#: written out, so reordering the cascade cannot leave these tests asserting
#: against values the probe no longer sends first.
LOW, HIGH = PAIRS[0]
NEXT_LOW, NEXT_HIGH = PAIRS[1]

#: What the fake engine returns: exit status, what it said, what it wrote.
#: ``None`` for the third means it wrote no readback at all.
Reply = tuple[int, str, str | None]


class FakeEngine:
    """An engine whose answer depends on the sentinel it was handed.

    Keyed by sentinel rather than by call order, because the property under test
    is now about *two* runs of one option and what differs between them. A
    call-ordered script would let a test pass while the probe sent the same value
    twice, which is exactly the thing that must not happen.
    """

    def __init__(self, sidecar: Path, reply: Callable[[str], Reply]) -> None:
        self.sidecar = sidecar
        self.reply = reply
        self.seen: list[str] = []

    @property
    def calls(self) -> int:
        return len(self.seen)

    def __call__(self, argv: list[str], *, timeout: float = 0.0) -> Completed:
        sentinel = next(a.split("=", 1)[1] for a in argv if a.startswith("--an-option="))
        self.seen.append(sentinel)
        status, said, writes = self.reply(sentinel)
        if writes is not None:
            self.sidecar.write_text(writes, encoding="utf-8")
        if status < 0:
            return Completed(argv=argv, exit_status=None, signal=None, timed_out=True)
        return Completed(argv=argv, exit_status=status, stderr=said)


def _ini(pairs: Mapping[str, str]) -> str:
    return "".join(f"{k} = {v}\n" for k, v in pairs.items())


def _dumps(per_sentinel: Mapping[str, Mapping[str, str]]) -> Callable[[str], Reply]:
    """Accept the named sentinels with the given dump; refuse every other."""

    def reply(sentinel: str) -> Reply:
        if sentinel in per_sentinel:
            return (0, "", _ini(per_sentinel[sentinel]))
        return (1, "Invalid value supplied", None)

    return reply


def _probe(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    reply: Callable[[str], Reply],
    *,
    volatile: tuple[str, ...] = (),
) -> tuple[ProbeOutcome, MapEntry, FakeEngine]:
    sidecar = tmp_path / "readback"
    engine = FakeEngine(sidecar, reply)
    monkeypatch.setattr("slicelab.engine.characterise.run", engine)
    assert _PROBE is not None
    entry = _probe_one(
        PRUSASLICER, FOUND, _PROBE, "an-option", sidecar, BASELINE, volatile, timeout=1.0
    )
    return entry.outcome, entry, engine


def test_every_sentinel_is_sent_as_a_pair_of_two_distinct_values() -> None:
    """The pair is the mechanism, so a degenerate one would silently disable it."""
    assert PAIRS, "the probe declares no sentinels"
    for low, high in PAIRS:
        assert low != high, f"sentinel pair {low!r}/{high!r} discriminates nothing"


def test_a_key_that_follows_the_value_is_the_mapping(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    outcome, entry, engine = _probe(
        tmp_path,
        monkeypatch,
        _dumps({LOW: {**BASELINE, "beta": LOW}, HIGH: {**BASELINE, "beta": HIGH}}),
    )
    assert outcome is ProbeOutcome.MAPPED
    assert entry == MapEntry(
        keys=("beta",),
        side_effects=(),
        tracking=Tracking.EXACT,
        outcome=ProbeOutcome.MAPPED,
    )
    assert entry.conclusive
    assert engine.seen == [LOW, HIGH], "one sentinel cannot establish tracking"


def test_an_aggregate_option_maps_to_every_member(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """``--extruder`` at ``=2`` then ``=3``: all three members follow the value.

    It is an aggregate, so every member IS the request. Keeping one of them and
    dropping two would let a readback report ``applied`` with two keys never
    looked at -- green over an intent only partly honoured.
    """
    outcome, entry, _ = _probe(
        tmp_path,
        monkeypatch,
        _dumps(
            {
                LOW: {"alpha": LOW, "beta": LOW, "gamma": LOW},
                HIGH: {"alpha": HIGH, "beta": HIGH, "gamma": HIGH},
            }
        ),
    )
    assert outcome is ProbeOutcome.MAPPED
    assert entry is not None
    assert entry.keys == ("alpha", "beta", "gamma")
    assert entry.tracking is Tracking.EXACT


def test_a_dependent_constraint_is_a_side_effect_and_never_a_key(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """``--spiral-vase`` at ``=1`` then ``=0``, which is `notes/critique.md` G4.

    Measured on 2.9.6 it moves five keys, and only ``spiral_vase`` follows the
    value. ``perimeters``, ``fill_density``, ``top_solid_layers`` and
    ``filament_retract_layer_change`` are the engine adjusting the print around a
    request that never named them -- on a slice PrusaSlicer performed exactly as
    designed. Adjudicating the authored value against those four is G4's false
    red, and one extra invocation separates them structurally.

    ``gamma`` here is the constraint: it moves, and it reads the same under both
    sentinels, which is the thing a key carrying the option's value cannot do.
    """
    outcome, entry, _ = _probe(
        tmp_path,
        monkeypatch,
        _dumps(
            {
                LOW: {**BASELINE, "beta": LOW, "gamma": "forced"},
                HIGH: {**BASELINE, "beta": HIGH, "gamma": "forced"},
            }
        ),
    )
    assert outcome is ProbeOutcome.MAPPED
    assert entry == MapEntry(
        keys=("beta",),
        side_effects=("gamma",),
        tracking=Tracking.EXACT,
        outcome=ProbeOutcome.MAPPED,
    )


def test_a_constraint_that_equals_the_sentinel_in_one_run_is_still_a_side_effect(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The case a one-sentinel value filter could never catch.

    ``--spiral-vase=1`` forces ``perimeters`` to ``1``, which is exactly the
    sentinel -- so "did this key take the value I sent" says yes about a key that
    was never requested. It takes the *second* run to see that it does not follow
    the value.
    """
    outcome, entry, _ = _probe(
        tmp_path,
        monkeypatch,
        _dumps(
            {
                LOW: {**BASELINE, "beta": LOW, "gamma": LOW},
                HIGH: {**BASELINE, "beta": HIGH, "gamma": LOW},
            }
        ),
    )
    assert entry is not None
    assert entry.keys == ("beta",)
    assert entry.side_effects == ("gamma",)


def test_a_key_that_normalises_the_value_is_mapped_inexactly_not_dropped(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Normalisation is the readback diff's problem, never a reason to unmap.

    ``--fill-density=0.17`` resolves to ``17%`` and ``--draft-shield=1`` to
    ``enabled``. The key responded to the value -- it reads differently under two
    different sentinels, which a dependent constraint does not -- so it is the
    option's key, and the entry says the tie is weaker rather than pretending
    there is none. Measured: a rule that required the value verbatim unmapped 89
    of 330 mapped options.
    """
    outcome, entry, _ = _probe(
        tmp_path,
        monkeypatch,
        _dumps(
            {
                NEXT_LOW: {**BASELINE, "beta": f"{NEXT_LOW}%"},
                NEXT_HIGH: {**BASELINE, "beta": f"{NEXT_HIGH}%"},
            }
        ),
    )
    assert outcome is ProbeOutcome.MAPPED
    assert entry == MapEntry(
        keys=("beta",),
        side_effects=(),
        tracking=Tracking.INEXACT,
        outcome=ProbeOutcome.MAPPED,
    )


def test_an_inexact_pair_does_not_stop_the_cascade(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """``--fill-density`` again, and the reason the cascade keeps going.

    The float pair is accepted and normalised, which is only an inexact tie. A
    later pair of the right type carries the value verbatim. Settling for the
    first non-empty answer would hand the readback a weaker entry than the engine
    was willing to give.
    """
    later_low, later_high = PAIRS[3]
    outcome, entry, engine = _probe(
        tmp_path,
        monkeypatch,
        _dumps(
            {
                NEXT_LOW: {**BASELINE, "beta": f"{NEXT_LOW}%"},
                NEXT_HIGH: {**BASELINE, "beta": f"{NEXT_HIGH}%"},
                later_low: {**BASELINE, "beta": later_low},
                later_high: {**BASELINE, "beta": later_high},
            }
        ),
    )
    assert entry is not None
    assert entry.tracking is Tracking.EXACT
    assert later_low in engine.seen


def test_a_new_key_is_a_mapping_and_not_a_namespace_change(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """``--bed-custom-texture`` adds a key the default dump does not have."""
    outcome, entry, _ = _probe(
        tmp_path,
        monkeypatch,
        _dumps({LOW: {**BASELINE, "delta": LOW}, HIGH: {**BASELINE, "delta": HIGH}}),
    )
    assert outcome is ProbeOutcome.MAPPED
    assert entry is not None and entry.keys == ("delta",)


def test_a_dump_that_lost_baseline_keys_is_a_mode_switch(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """``--export-sla`` swaps the whole key namespace; that is not a mapping.

    Measured on 2.9.6: it drops 334 of the 343 baseline keys and adds 143 of its
    own. Reading the difference as "this option writes 480 keys" is the shape the
    prototype produced, and no count threshold is needed to refuse it -- a config
    option never removes a key.
    """
    outcome, entry, _ = _probe(tmp_path, monkeypatch, _dumps({LOW: {"sla_only": "1"}}))
    assert (outcome, entry.keys, entry.tracking) == (
        ProbeOutcome.NAMESPACE_CHANGED,
        (),
        None,
    )
    assert not entry.conclusive


def test_exit_zero_with_no_artifact_is_not_a_mapping(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """D7, aimed at the probe. ``--post-process`` and ``--info`` do exactly this.

    Without the gate the absent file parses to ``{}``, every baseline key reads as
    moved, and one option is recorded as writing all 343.
    """
    outcome, entry, _ = _probe(tmp_path, monkeypatch, lambda s: (0, "", None))
    assert (outcome, entry.keys) == (ProbeOutcome.NO_ARTIFACT, ())
    assert not entry.conclusive, "an engine that wrote nothing established nothing"


def test_an_empty_artifact_counts_as_no_artifact(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Zero bytes parse to zero keys, which is the same false fan-out."""
    outcome, _, _ = _probe(tmp_path, monkeypatch, lambda s: (0, "", ""))
    assert outcome is ProbeOutcome.NO_ARTIFACT


def test_an_engine_that_never_returns_is_not_an_engine_that_refused(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """``--gcodeviewer`` opens a window and waits. It must cost one timeout, once."""
    outcome, _, engine = _probe(tmp_path, monkeypatch, lambda s: (-1, "", None))
    assert outcome is ProbeOutcome.TIMED_OUT
    assert engine.calls == 1, "a hang must not be retried once per sentinel"


def test_an_option_the_engine_does_not_have_stops_at_the_first_sentinel(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    outcome, _, engine = _probe(
        tmp_path, monkeypatch, lambda s: (1, "Unknown option --an-option", None)
    )
    assert outcome is ProbeOutcome.UNKNOWN_OPTION
    assert engine.calls == 1


def test_a_bad_value_costs_a_sentinel_and_not_the_option(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Options are typed: a rejection is "wrong value", not "no such option"."""
    outcome, entry, engine = _probe(
        tmp_path,
        monkeypatch,
        _dumps(
            {
                NEXT_LOW: {**BASELINE, "beta": NEXT_LOW},
                NEXT_HIGH: {**BASELINE, "beta": NEXT_HIGH},
            }
        ),
    )
    assert outcome is ProbeOutcome.MAPPED
    assert entry is not None and entry.keys == ("beta",)
    assert engine.seen == [LOW, NEXT_LOW, NEXT_HIGH], (
        "a refused first value must not cost the pair's second run"
    )


def test_every_sentinel_refused_is_a_could_not_tell(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    outcome, entry, engine = _probe(
        tmp_path, monkeypatch, lambda s: (1, "Invalid value supplied", None)
    )
    assert (outcome, entry.keys) == (ProbeOutcome.REJECTED, ())
    assert not entry.conclusive
    assert engine.calls == len(PAIRS), "a refused low value must not trigger the high one"


def test_an_accepted_option_that_moved_nothing_is_not_in_the_map(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """And only after every pair has been tried, not the first."""
    outcome, entry, engine = _probe(tmp_path, monkeypatch, lambda s: (0, "", _ini(BASELINE)))
    assert (outcome, entry.keys) == (ProbeOutcome.NO_KEY_MOVED, ())
    assert entry.conclusive, "writing no key is a finding, not a could-not-tell"
    assert engine.calls == 2 * len(PAIRS)


def test_a_sentinel_that_resolves_to_the_default_is_not_an_answer(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The defect this probe shipped for one measurement, as a regression test.

    D5: PrusaSlicer's boolean options validate nothing, and anything that is not
    literally ``1`` resolves to ``0``. ``--spiral-vase=SLICELABPROBE`` therefore
    exits 0, resolves to the ``0`` already in the dump, and moves no key. Stopping
    at the first accepted sentinel classified 110 real options -- ``--spiral-vase``,
    ``--support-material`` and ``--thin-walls`` among them -- as writing no
    configuration, which is the opposite of the truth and would keep every one of
    them out of the map.
    """
    true_word, false_word = PAIRS[4]
    outcome, entry, _ = _probe(
        tmp_path,
        monkeypatch,
        lambda s: (
            (0, "", _ini({**BASELINE, "beta": true_word}))
            if s == true_word
            else (0, "", _ini({**BASELINE, "beta": false_word}))
        ),
    )
    assert outcome is ProbeOutcome.MAPPED
    assert entry is not None and entry.keys == ("beta",)


def test_a_key_that_will_not_hold_still_is_not_attributed_to_the_option(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A key that differs between two identical baselines differs under every option.

    Left in, it would put a plausible extra key on every entry in the map. D8's
    habit -- reproducibility is measured, never assumed -- applied to the thing
    the whole map is diffed against.
    """
    outcome, entry, _ = _probe(
        tmp_path,
        monkeypatch,
        _dumps(
            {
                LOW: {**BASELINE, "alpha": "clock-a", "beta": LOW},
                HIGH: {**BASELINE, "alpha": "clock-b", "beta": HIGH},
            }
        ),
        volatile=("alpha",),
    )
    assert outcome is ProbeOutcome.MAPPED
    assert entry == MapEntry(
        keys=("beta",),
        side_effects=(),
        tracking=Tracking.EXACT,
        outcome=ProbeOutcome.MAPPED,
    )


def test_a_stale_readback_is_never_read_as_this_option_s_answer(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The sidecar is one path reused by every probe, so a leftover is data.

    The harm is precise, and a weaker version of this test missed it. Every exit
    from a run already removes the file, so within one process the only window is
    a file left by something *else* -- a previous characterisation killed
    mid-sweep, say. Plant one, then have the engine exit 0 writing nothing for
    the first sentinel and write a real dump for the second: without the
    clear-before-run, the stale file becomes the first half of a comparison and
    this option is mapped to whatever the last one wrote. With it, the first run
    is honestly ``no-artifact``.

    The earlier fixture had the engine write nothing for *both* sentinels, so the
    second run found the file already removed and the outcome came out
    ``no-artifact`` either way. It passed against the missing clear -- the
    mutation sweep is what said so.
    """
    sidecar = tmp_path / "readback"
    stale = _ini({**BASELINE, "beta": "LEFT-BY-THE-LAST-OPTION"})
    sidecar.write_text(stale, encoding="utf-8")

    def reply(sentinel: str) -> Reply:
        if sentinel == LOW:
            return (0, "", None)
        return (0, "", _ini({**BASELINE, "beta": HIGH}))

    engine = FakeEngine(sidecar, reply)
    monkeypatch.setattr("slicelab.engine.characterise.run", engine)
    assert _PROBE is not None
    entry = _probe_one(PRUSASLICER, FOUND, _PROBE, "an-option", sidecar, BASELINE, (), timeout=1.0)
    assert entry.outcome is ProbeOutcome.NO_ARTIFACT, (
        f"the engine wrote nothing, so the answer is no-artifact; got {entry.outcome} "
        f"with keys {entry.keys} -- read out of a file the last option left behind"
    )
    assert entry.keys == ()


def test_the_sidecar_does_not_outlive_a_failed_probe(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Every exit from a run removes it, including the ones that raise nothing."""
    sidecar = tmp_path / "readback"
    engine = FakeEngine(sidecar, lambda s: (-1, "", _ini(BASELINE)))
    monkeypatch.setattr("slicelab.engine.characterise.run", engine)
    assert _PROBE is not None
    entry = _probe_one(PRUSASLICER, FOUND, _PROBE, "an-option", sidecar, BASELINE, (), timeout=1.0)
    assert entry.outcome is ProbeOutcome.TIMED_OUT
    assert not sidecar.exists(), "a timed-out probe left its readback for the next option"


def test_an_option_the_probe_could_not_settle_reaches_the_caller_as_such(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The G2 defect's route back in, closed.

    A timed-out option used to be simply missing from the map, which is what an
    option that does not exist also looks like. A readback cannot tell those
    apart, so it says ``absent`` -- a claim about the engine -- for a key it
    never measured, and one bad afternoon of host load turns into a green run
    over an unhonoured intent. The outcome travels with the entry so the caller
    can refuse instead.
    """
    _, timed_out, _ = _probe(tmp_path, monkeypatch, lambda s: (-1, "", None))
    _, measured, _ = _probe(tmp_path, monkeypatch, lambda s: (0, "", _ini(BASELINE)))

    assert timed_out.keys == measured.keys == ()
    assert measured.conclusive, "the engine answered: this option writes no key"
    assert not timed_out.conclusive, "the engine never answered"
    assert timed_out.outcome is not measured.outcome


def test_an_option_that_reads_inert_is_asked_a_second_time(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """`no-key-moved` is a finding, and a transient failure looks exactly like it.

    Measured across two full sweeps, `--enable-dynamic-overhang-speeds` came back
    `mapped` in one and `no-key-moved` in the other while mapping 3/3 when probed
    alone. That residue lands in a **conclusive** bucket, so the could-not-tell
    channel does not catch it -- which is why this set, and only this set, is
    re-probed.

    A disagreement demotes to `unstable`. Promoting the more interesting answer
    would be picking a winner between two runs that disagreed.
    """
    sidecar = tmp_path / "readback"
    calls = {"n": 0}

    def reply(sentinel: str) -> Reply:
        # Inert on the first full cascade; on the confirmation pass the key moves.
        calls["n"] += 1
        if calls["n"] <= 2 * len(PAIRS):
            return (0, "", _ini(BASELINE))
        return (0, "", _ini({**BASELINE, "beta": sentinel}))

    engine = FakeEngine(sidecar, reply)
    monkeypatch.setattr("slicelab.engine.characterise.run", engine)
    assert _PROBE is not None
    entries = {
        "an-option": _probe_one(
            PRUSASLICER, FOUND, _PROBE, "an-option", sidecar, BASELINE, (), timeout=1.0
        )
    }
    assert entries["an-option"].outcome is ProbeOutcome.NO_KEY_MOVED

    _confirm_the_inert(entries, PRUSASLICER, FOUND, _PROBE, sidecar, BASELINE, (), timeout=1.0)
    assert entries["an-option"].outcome is ProbeOutcome.UNSTABLE
    assert not entries["an-option"].conclusive, (
        "two runs that disagreed established nothing a caller may act on"
    )
    assert entries["an-option"].keys == ()


def test_characterise_actually_runs_the_confirmation_pass(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The call site, not the function body -- and nothing was checking it.

    The three tests around this one call ``_confirm_the_inert`` directly, so
    deleting its call from ``characterise`` left the whole suite green, engine
    tests included. The feature could be removed and ship. Mutation-testing the
    function's *body* looked like coverage and was measuring the wrong site.

    So this drives ``characterise`` end to end against a stand-in engine and
    asserts the outcome only the confirmation pass can produce: an option that
    reads inert on the first cascade and moves on the second is ``unstable``,
    where without the pass it would be a conclusive ``no-key-moved``.
    """
    monkeypatch.setenv("XDG_CACHE_HOME", str(tmp_path))
    monkeypatch.setattr("slicelab.engine.characterise.discover", lambda spec: FOUND)

    seen: list[str] = []

    def reply(argv: list[str], *, timeout: float = 0.0) -> Completed:
        saves = [a.split("=", 1)[1] for a in argv if a.startswith("--save=")]
        if not saves:  # the enumeration run, which this spec answers from nothing
            return Completed(argv=argv, exit_status=0)
        sidecar = saves[0]
        option = [a for a in argv if a.startswith("--an-option=")]
        if not option:  # the two baseline dumps
            Path(sidecar).write_text(_ini(BASELINE), encoding="utf-8")
            return Completed(argv=argv, exit_status=0)
        sentinel = option[0].split("=", 1)[1]
        seen.append(sentinel)
        # Inert for the whole first cascade; responsive for the confirmation one.
        moved = BASELINE if len(seen) <= 2 * len(PAIRS) else {**BASELINE, "beta": sentinel}
        Path(sidecar).write_text(_ini(moved), encoding="utf-8")
        return Completed(argv=argv, exit_status=0)

    monkeypatch.setattr("slicelab.engine.characterise.run", reply)
    probe = PRUSASLICER.option_probe
    assert probe is not None
    spec = replace(
        PRUSASLICER,
        option_probe=replace(probe, candidates=lambda listing, baseline: ("an-option",)),
    )

    result = characterise(spec, "under-test")
    entry = result.entries["an-option"]
    assert entry.outcome is ProbeOutcome.UNSTABLE, (
        f"characterise() returned {entry.outcome}; the confirmation pass never ran"
    )
    assert not entry.conclusive
    assert result.inconclusive == ("an-option",)
    assert len(seen) > 2 * len(PAIRS), "the option was probed only once"


def test_a_stable_inert_option_survives_the_confirmation_pass(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The pass must not turn every honest negative into a could-not-tell."""
    sidecar = tmp_path / "readback"
    engine = FakeEngine(sidecar, lambda s: (0, "", _ini(BASELINE)))
    monkeypatch.setattr("slicelab.engine.characterise.run", engine)
    assert _PROBE is not None
    entries = {
        "an-option": _probe_one(
            PRUSASLICER, FOUND, _PROBE, "an-option", sidecar, BASELINE, (), timeout=1.0
        )
    }
    _confirm_the_inert(entries, PRUSASLICER, FOUND, _PROBE, sidecar, BASELINE, (), timeout=1.0)
    assert entries["an-option"].outcome is ProbeOutcome.NO_KEY_MOVED
    assert entries["an-option"].conclusive


def test_the_confirmation_pass_never_asks_again_about_a_refusal(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Only the inert set. A retry over a refusal suppresses a real refusal.

    ``rejected`` means the engine turned every value down, and ``timed-out``
    means it hung -- re-probing the first hides a genuine "no" behind a lucky
    second run, and re-probing the second is what poisons the host. Both are
    already could-not-tells, so a retry buys nothing and costs the property.
    """
    sidecar = tmp_path / "readback"
    engine = FakeEngine(sidecar, lambda s: (0, "", _ini(BASELINE)))
    monkeypatch.setattr("slicelab.engine.characterise.run", engine)
    assert _PROBE is not None
    entries = {
        "refused": _unmapped(ProbeOutcome.REJECTED),
        "hung": _unmapped(ProbeOutcome.TIMED_OUT),
        "silent": _unmapped(ProbeOutcome.NO_ARTIFACT),
        "switched": _unmapped(ProbeOutcome.NAMESPACE_CHANGED),
    }
    before = dict(entries)
    _confirm_the_inert(entries, PRUSASLICER, FOUND, _PROBE, sidecar, BASELINE, (), timeout=1.0)
    assert entries == before
    assert engine.calls == 0, "the confirmation pass reached an option it must not touch"


def test_a_characterisation_says_when_it_is_partial() -> None:
    """A partial map that cannot say it is partial is what this project refuses."""
    whole = Characterisation(
        "e",
        "1",
        {
            "a": MapEntry(("a",), (), Tracking.EXACT, ProbeOutcome.MAPPED),
            "b": _unmapped(ProbeOutcome.NO_KEY_MOVED),
        },
        1,
        (),
    )
    assert whole.inconclusive == ()

    partial = Characterisation(
        "e", "1", {**whole.entries, "c": _unmapped(ProbeOutcome.TIMED_OUT)}, 1, ()
    )
    assert partial.inconclusive == ("c",)


def test_an_inexact_entry_claims_no_side_effects(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Because an inexact pair did not separate them, and guessing would be worse.

    ``INEXACT`` does not only mean "the value was normalised". It means the pair
    that answered did not carry either value verbatim, which is exactly the
    condition under which a dependent constraint is indistinguishable from a
    write -- so the entry claims no separation rather than an arbitrary one.
    """
    _, entry, _ = _probe(
        tmp_path,
        monkeypatch,
        _dumps(
            {
                LOW: {**BASELINE, "beta": "normalised-low", "gamma": "forced"},
                HIGH: {**BASELINE, "beta": "normalised-high", "gamma": "forced"},
            }
        ),
    )
    assert entry.tracking is Tracking.INEXACT
    assert entry.side_effects == ()
    assert "gamma" not in entry.keys, "a key that did not respond is not the option's"


# -- the cache: what it is keyed by, and what it refuses to believe -----------


def test_the_cache_is_keyed_by_engine_and_by_version(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The map is a per-build fact, so one engine's two builds are two files.

    A map carried across a release is confidently wrong in exactly the direction
    this project refuses: options are renamed and keys are added between versions,
    and nothing would report the gap.
    """
    monkeypatch.setenv("XDG_CACHE_HOME", str(tmp_path))
    here = cache_path_for(PRUSASLICER, "2.9.6")
    later = cache_path_for(PRUSASLICER, "2.10.0")
    other = cache_path_for(ORCASLICER, "2.9.6")
    assert here != later != other and here != other
    assert tmp_path in here.parents
    assert PRUSASLICER.name in here.parts and "2.9.6" in here.parts


def test_a_relative_cache_home_is_ignored(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """The basedir spec says a relative value MUST be ignored.

    Honouring one scatters a cache directory wherever the user was standing, which
    is the defect ``launch._scratch_roots`` was written about.
    """
    monkeypatch.setenv("XDG_CACHE_HOME", "relative-cache")
    monkeypatch.chdir(tmp_path)
    assert Path.home() in _cache_root().parents


@pytest.mark.parametrize(
    ("version", "expected"),
    [
        ("2.9.6", "2.9.6"),
        # A real one. `Identity` reads this off the Flathub build's own banner, and
        # `+` and `.` have to survive or two builds share one cache entry.
        ("2.9.6+flathub.org", "2.9.6+flathub.org"),
    ],
)
def test_a_real_version_reaches_the_cache_path_intact(version: str, expected: str) -> None:
    assert _safe(version) == expected


@pytest.mark.parametrize("version", ["../../etc", "a/b", "...", "   ", "", ".", "..", "a\0b"])
def test_a_version_can_never_climb_out_of_the_cache_directory(version: str) -> None:
    """A build states its own version and slicelab does not get to assume what is in it.

    Asserted as the property rather than as an expected string: what matters is
    that the result is one path segment which is neither empty nor a traversal,
    not which character each rejected one became.
    """
    safe = _safe(version)
    assert safe and safe not in (".", "..")
    assert Path(safe).parts == (safe,)


def test_the_cache_round_trips_tuples_rather_than_lists(tmp_path: Path) -> None:
    result = Characterisation(
        engine="e",
        version="1",
        entries={
            "extruder": MapEntry(
                keys=("infill_extruder", "perimeter_extruder"),
                side_effects=("solid_infill_extruder",),
                tracking=Tracking.EXACT,
                outcome=ProbeOutcome.MAPPED,
            ),
            "info": _unmapped(ProbeOutcome.NO_ARTIFACT),
        },
        baseline_key_count=343,
        volatile_keys=(),
    )
    path = tmp_path / "m.json"
    _write_cache(path, result)
    read = _read_cache(path)
    assert read is not None
    assert read["extruder"] == result.entries["extruder"], (
        "tracking and side effects must survive the cache"
    )
    assert read["info"].outcome is ProbeOutcome.NO_ARTIFACT
    assert not read["info"].conclusive


def test_the_cache_records_why_an_option_is_not_in_the_map(tmp_path: Path) -> None:
    """An unmapped option must be a fact with a cause, not an absence.

    That is what lets a caller refuse it at 64 -- slicelab's own argv is wrong --
    rather than reporting it as ``absent``, which is a claim about the engine.
    """
    path = tmp_path / "m.json"
    _write_cache(
        path,
        Characterisation(
            "e",
            "1",
            {
                "a": MapEntry(
                    keys=("a",),
                    side_effects=("z",),
                    tracking=Tracking.EXACT,
                    outcome=ProbeOutcome.MAPPED,
                ),
                "b": _unmapped(ProbeOutcome.NO_KEY_MOVED),
                "c": _unmapped(ProbeOutcome.TIMED_OUT),
            },
            1,
            (),
        ),
    )
    document = json.loads(path.read_text(encoding="utf-8"))
    assert document["entries"]["b"]["outcome"] == "no-key-moved"
    assert document["entries"]["c"]["outcome"] == "timed-out"
    assert document["entries"]["a"]["side_effects"] == ["z"]
    assert document["entries"]["a"]["tracking"] == "exact"
    assert document["inconclusive"] == 1


@pytest.mark.parametrize(
    "content",
    [
        "not json at all",
        # A document that is valid in every respect EXCEPT its schema, so that
        # only the schema guard can reject it. The obvious fixture --
        # `{"schema": 999, "entries": {"a": {"keys": ["b"]}}}` -- is malformed
        # twice over and was rejected by the entry-shape check instead, which
        # left the schema guard with no red state. Mutation-tested: removing the
        # schema check now reddens this case and nothing else.
        '{"schema": 999, "entries": {"a": {"keys": ["b"], "side_effects": [],'
        ' "tracking": "exact", "outcome": "mapped"}}}',
        '{"schema": 3, "entries": {}}',
        '{"schema": 3, "entries": {"a": ["b"]}}',
        '{"schema": 3, "entries": {"a": {"keys": "b"}}}',
        '{"schema": 3, "entries": {"a": {"keys": [], "side_effects": [],'
        ' "tracking": null, "outcome": "who-knows"}}}',
        '{"schema": 3}',
        '{"schema": 3, "map": {"a": ["b"]}}',
        "[]",
    ],
)
def test_a_cache_that_is_not_the_shape_we_wrote_is_a_miss(tmp_path: Path, content: str) -> None:
    """Re-measure rather than adapt. The engine is the authority; this is a receipt.

    An empty map is refused too: it is indistinguishable from a probe that reached
    nothing, and returning it would make every option read as unmapped.
    """
    path = tmp_path / "m.json"
    path.write_text(content, encoding="utf-8")
    assert _read_cache(path) is None


def test_a_missing_cache_is_a_miss(tmp_path: Path) -> None:
    assert _read_cache(tmp_path / "nothing.json") is None


def test_a_cached_map_is_returned_without_touching_the_engine(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("XDG_CACHE_HOME", str(tmp_path))
    _write_cache(
        cache_path_for(PRUSASLICER, "2.9.6"),
        Characterisation(
            "prusaslicer",
            "2.9.6",
            {
                "after-layer-gcode": MapEntry(
                    keys=("layer_gcode",),
                    side_effects=(),
                    tracking=Tracking.EXACT,
                    outcome=ProbeOutcome.MAPPED,
                )
            },
            1,
            (),
        ),
    )

    def refuse(*args: object, **kwargs: object) -> Characterisation:
        raise AssertionError("a cache hit must not reach the engine")

    monkeypatch.setattr("slicelab.engine.characterise.characterise", refuse)
    served = load_name_map(PRUSASLICER, "2.9.6")
    assert served["after-layer-gcode"].keys == ("layer_gcode",)
    assert served["after-layer-gcode"].tracking is Tracking.EXACT


def test_a_build_that_will_not_state_its_version_is_refused(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """``Identity.exact`` is False here, and caching under "" would poison the next build.

    The refusal must come **before** the engine is touched, not after a few
    hundred invocations produce a map with nowhere honest to put it -- so the
    probe is replaced with something that fails loudly if it is reached.
    """
    monkeypatch.setenv("XDG_CACHE_HOME", str(tmp_path))

    def refuse(*args: object, **kwargs: object) -> Characterisation:
        raise AssertionError("an unknown version must be refused before probing")

    monkeypatch.setattr("slicelab.engine.characterise.characterise", refuse)
    with pytest.raises(CharacterisationError, match="per-build"):
        load_name_map(PRUSASLICER, "  ")


def test_an_engine_with_no_probe_is_refused_rather_than_guessed_at() -> None:
    """The alternative to refusing is the transform G2 reproduced a false absent from."""
    with pytest.raises(CharacterisationError, match="transform"):
        characterise(replace(PRUSASLICER, option_probe=None), "2.9.6")


def test_an_engine_with_no_readback_is_refused() -> None:
    with pytest.raises(CharacterisationError, match="dump"):
        characterise(replace(PRUSASLICER, readback_flag=None), "2.9.6")


# -- the boundary: the driver must stay ignorant of every engine ---------------


def _imported_modules(path: Path) -> set[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    names: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            names.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module and node.level == 0:
            names.add(node.module)
    return names


def test_the_probe_driver_imports_no_adapter_module() -> None:
    """It may know that engines exist. It may not know which one it is driving.

    ``slicelab.adapters`` is the facade holding ``EngineSpec`` and ``OptionProbe``;
    reaching past it to ``slicelab.adapters.prusaslicer`` is how ``--help-fff``
    parsing would arrive in the core, one convenience at a time.
    """
    imported = _imported_modules(PACKAGE / "engine" / "characterise.py")
    reached = sorted(m for m in imported if m.startswith("slicelab.adapters."))
    assert reached == [], f"the probe driver reached into an adapter: {reached}"


def test_the_import_boundary_test_is_not_vacuous() -> None:
    """The adapter modules must be reachable, or the check above finds nothing."""
    imported = _imported_modules(PACKAGE / "adapters" / "__init__.py")
    assert any(m.startswith("slicelab.adapters.") for m in imported)


# -- against a real engine -----------------------------------------------------


#: What an engine config key looks like on both installed engines: lowercase,
#: digits, and at least one underscore joining segments -- ``layer_gcode``,
#: ``wall_loops``, ``spiral_vase``, ``sparse_infill_density``. Measured: no key on
#: either engine has an uppercase letter, a dash, or a single segment.
_KEY_SHAPED = re.compile(r"^[a-z][a-z0-9]*(?:_[a-z0-9]+)+$")

#: slicelab's own key-shaped terms under ``slicelab/engine/``, and the only ones
#: allowed there. Thirteen entries, each a field or member this package defines.
#:
#: **A whitelist, not an exemption rule**, and that is the whole correction. Two
#: earlier revisions tried to derive the exemption from the source: first "any
#: name the module binds", which let ``layer_gcode = "layer_gcode"`` exempt
#: itself, and then "any class-body field or enum member" -- which is the
#: *identical set* ``_schema_names`` contributes to ``undeclared_terms``, so it
#: subtracted exactly what it was supposed to catch and made the class body
#: structurally invisible. Measured: ``class Keys: layer_gcode = "layer_gcode"``,
#: ``class R: layer_gcode: str = "unset"`` and ``class K(StrEnum): LAYER_GCODE =
#: auto()`` all passed. Those are precisely the three leaks ``_schema_names``'
#: own docstring exists to name.
#:
#: Any rule that derives the exemption from the code being checked is exemptible
#: by writing the code. D26 reached the same conclusion for the core modules and
#: answered it with a declared vocabulary; this is that answer, scoped to the
#: config-key shape so the list stays short. **An engine's key can never be added
#: here** -- that is the entire content of the rule, and adding an entry happens
#: in a diff where someone can object.
ENGINE_PACKAGE_TERMS = frozenset(
    {
        # `ProbeOutcome` members and `Characterisation` / `MapEntry` fields.
        "namespace_changed",
        "no_artifact",
        "no_key_moved",
        "timed_out",
        "unknown_option",
        "baseline_key_count",
        "side_effects",
        "volatile_keys",
        # `LaunchKind` and `LaunchForm`.
        "flatpak_bypass",
        "argv_prefix",
        # `Identity` and `Completed`.
        "digest_of",
        "exit_status",
        # The XDG base-directory spec's own variable name.
        "xdg_cache_home",
    }
)


def key_shaped_strangers(source: str, filename: str = "<test>") -> list[str]:
    """Config-key-shaped terms that are not slicelab's own.

    Case-folded before matching, because a ``StrEnum`` member is uppercase and
    carries the lowercase value: ``LAYER_GCODE = auto()`` *is* ``"layer_gcode"``
    with no such literal in the file, and a lowercase-only test misses it twice
    over -- once on the shape and once on the name.
    """
    return sorted(
        {
            term
            for term in undeclared_terms(source, filename)
            if _KEY_SHAPED.match(term.lower()) and term.lower() not in ENGINE_PACKAGE_TERMS
        }
    )


def test_no_engine_shaped_key_reaches_the_engine_package() -> None:
    """The boundary guard that survives a runner with no slicer.

    ``test_no_live_engine_key_or_option_appears_outside_the_adapters`` below is
    the stronger claim and it **skips** without an engine -- and ``ci.yml``
    installs none, so on a pull request it checks nothing. ``engine.yml`` has the
    slicers and runs on dispatch and a weekly cron. A guard that never runs on
    the change that would break it is the shape this org exists to refuse, so
    here is the part of it that needs no engine.

    An engine config key is lowercase, digit-bearing and underscore-joined on
    both installed engines. A literal of that shape in ``slicelab/engine/`` is
    either a name the module already defines -- a dataclass field spelled twice
    for a dict key, an enum value -- or it came from outside, and outside is
    where the engines are.
    """
    package = PACKAGE / "engine"
    offenders: list[str] = []
    for path in sorted(package.glob("*.py")):
        source = path.read_text(encoding="utf-8")
        offenders += [
            f"{path.relative_to(PACKAGE)} names {term!r}"
            for term in key_shaped_strangers(source, str(path))
        ]
    assert offenders == [], (
        "a config-key-shaped literal reached slicelab/engine/ without being a "
        f"name the module defines: {offenders}. If it is an engine's key it "
        "belongs under slicelab/adapters/."
    )


def test_the_engine_shaped_guard_catches_a_real_key() -> None:
    """Red-capability, against deliberately dirty source rather than the tree.

    ``wall_loops`` is OrcaSlicer's and ``layer_gcode`` is PrusaSlicer's; both are
    real keys this repository must never learn outside ``adapters/``.
    """
    dirty = 'def f(readback):\n    return readback["wall_loops"] or "layer_gcode" in readback\n'
    assert key_shaped_strangers(dirty) == ["layer_gcode", "wall_loops"]


@pytest.mark.parametrize(
    ("shape", "source", "expected"),
    [
        ("module-level binding", 'layer_gcode = "layer_gcode"\n', "layer_gcode"),
        (
            "local binding",
            'def f():\n    wall_loops = "wall_loops"\n    return wall_loops\n',
            "wall_loops",
        ),
        ("class-body assignment", 'class Keys:\n    layer_gcode = "layer_gcode"\n', "layer_gcode"),
        (
            "dataclass field",
            "from dataclasses import dataclass\n@dataclass\nclass R:\n"
            '    layer_gcode: str = "unset"\n',
            "layer_gcode",
        ),
        (
            "StrEnum member carrying the value",
            "from enum import StrEnum, auto\nclass K(StrEnum):\n    LAYER_GCODE = auto()\n",
            "LAYER_GCODE",
        ),
        ("subscript", 'def f(rb):\n    return rb["spiral_vase"]\n', "spiral_vase"),
    ],
    # Named ids, so a failure says which shape evaded rather than echoing the
    # whole source fixture -- and so a mutation can be aimed at one of them.
    ids=[
        "module-level-binding",
        "local-binding",
        "class-body-assignment",
        "dataclass-field",
        "strenum-member",
        "subscript",
    ],
)
def test_the_engine_shaped_guard_catches_every_shape_a_key_can_arrive_in(
    shape: str, source: str, expected: str
) -> None:
    """The five evasions two earlier revisions of this guard allowed.

    Both tried to derive the exemption from the source being checked -- first
    "any name the module binds", then "any class-body field or enum member" --
    and a rule of that kind is exemptible by writing the code it inspects. The
    second was worse than the first: it subtracted exactly the set
    ``_schema_names`` contributes, so the class body became invisible and the
    three shapes that docstring exists to name all passed.

    ``LAYER_GCODE = auto()`` is the sharpest: it carries the value
    ``"layer_gcode"`` with no such literal in the file, and it evades a
    lowercase-only test twice over -- once on the shape and once on the name.
    """
    assert expected in key_shaped_strangers(source), f"{shape} evaded the guard"


def test_the_engine_shaped_guard_does_not_flag_our_own_field_names() -> None:
    """A guard on the guard: it must not be red on every dataclass we write."""
    ours = (
        "from dataclasses import dataclass\n"
        "@dataclass\n"
        "class R:\n"
        "    exit_status: int\n"
        "def f(r):\n"
        '    return {"exit_status": r.exit_status}\n'
    )
    assert key_shaped_strangers(ours) == []


def _live_vocabulary(spec: EngineSpec, tmp_path: Path) -> tuple[tuple[str, ...], Mapping[str, str]]:
    """This build's own option names and config keys, read from the engine."""
    from slicelab.engine.discover import discover

    probe = spec.option_probe
    assert probe is not None and spec.readback_flag is not None
    found = discover(spec)
    if found.form is None:
        pytest.skip(f"{spec.name}: {found.reason}")
    sidecar = tmp_path / "readback"
    run(argv_for(found.form, (f"{spec.readback_flag}={sidecar}",), (str(sidecar),)), timeout=90.0)
    if not sidecar.exists() or sidecar.stat().st_size == 0:
        pytest.skip(f"{spec.name} wrote no readback for a request with nothing set")
    baseline = probe.read_config(sidecar.read_text(encoding="utf-8", errors="replace"))
    listing = ""
    if probe.enumerate_argv:
        completed = run(argv_for(found.form, probe.enumerate_argv, ()), timeout=90.0)
        listing = completed.stdout + completed.stderr
    return probe.candidates(listing, baseline), baseline


def _scanned_sources() -> list[Path]:
    """Every module outside ``adapters/``. The claim is about all of them."""
    adapters = PACKAGE / "adapters"
    return [p for p in sorted(PACKAGE.rglob("*.py")) if adapters not in p.parents]


def test_no_live_engine_key_or_option_appears_outside_the_adapters(
    any_engine: EngineSpec, tmp_path: Path
) -> None:
    """D26's claim, measured against the vocabulary the engine states today.

    ``tests/test_names_confined.py`` scans the modules directly under
    ``slicelab/``; ``slicelab/engine/`` is not among them, and the probe driver
    lives there. Rather than widen that decision's whitelist -- the dumping ground
    its supersede clause warns about -- the same claim is made the expensive way:
    read this build's own config keys, and require that not one of them survives
    ``undeclared_terms`` anywhere outside ``slicelab/adapters/``.

    Reusing that function rather than scanning words is not incidental. A blanket
    "no engine word anywhere" scan is red on day one, because ``output``,
    ``load``, ``save`` and ``info`` are engine option names and ordinary English
    at the same time -- measured against this corpus, a word scan flags 54 terms
    across eleven clean modules, nearly all of them prose. D26 settled that
    already: a literal is either prose or vocabulary, and prose is not a leak.

    Scoped to the **config-key namespace**, which is D26's own scope rather than a
    convenient narrowing. The option names are the map's keys and the config keys
    are its values, and only the values are what a readback compares against.
    Putting the option names back costs exactly one false positive, worth naming
    because it is the shape of the whole problem: ``engine/identity.py`` runs
    ``flatpak info`` to read a deployment commit, and ``--info`` is also a
    PrusaSlicer option, so the literal ``"info"`` there is a Flatpak subcommand
    colliding with an engine option and not a leak of anything.
    """
    _options, baseline = _live_vocabulary(any_engine, tmp_path)
    vocabulary = set(baseline)
    assert len(vocabulary) > 200, (
        f"{any_engine.name} stated {len(vocabulary)} keys; it was not read"
    )

    offenders: list[str] = []
    for path in _scanned_sources():
        terms = set(undeclared_terms(path.read_text(encoding="utf-8"), str(path)))
        for term in sorted(vocabulary & terms):
            offenders.append(f"{path.relative_to(PACKAGE)} names {term!r}")
    assert offenders == [], (
        "an engine's own vocabulary reached a literal outside slicelab/adapters/: "
        + "; ".join(offenders)
    )


def test_the_live_vocabulary_check_can_go_red(any_engine: EngineSpec, tmp_path: Path) -> None:
    """A guard on the guard: the scan must catch a term that really is in the corpus."""
    options, baseline = _live_vocabulary(any_engine, tmp_path)
    assert options and baseline
    sample = sorted(baseline)[0]
    assert sample in set(undeclared_terms(f'def f(rb):\n    return rb["{sample}"]\n'))


def test_the_engine_writes_a_key_the_options_name_does_not_predict(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """G2's reproduction, as a test rather than a paragraph.

    ``--after-layer-gcode`` writes ``layer_gcode``. A dash-to-underscore readback
    looks for ``after_layer_gcode``, does not find it, and reports ``absent`` on a
    key the engine applied exactly -- forcing exit 2 on a correct run.
    """
    from slicelab.engine.discover import ExitFidelity as Fidelity
    from slicelab.engine.discover import discover

    found = discover(PRUSASLICER)
    if found.fidelity is not Fidelity.ESTABLISHED:
        pytest.skip(f"prusaslicer: {found.reason}")
    monkeypatch.setenv("XDG_CACHE_HOME", str(tmp_path))
    probe = PRUSASLICER.option_probe
    assert probe is not None
    spec = replace(
        PRUSASLICER,
        option_probe=replace(probe, candidates=lambda listing, baseline: ("after-layer-gcode",)),
    )
    result = characterise(spec, "under-test")
    assert result.name_map["after-layer-gcode"] == ("layer_gcode",)


def test_one_option_can_write_several_keys(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """``--extruder`` writes three. A ``str`` value would have to drop two of them."""
    from slicelab.engine.discover import ExitFidelity as Fidelity
    from slicelab.engine.discover import discover

    found = discover(PRUSASLICER)
    if found.fidelity is not Fidelity.ESTABLISHED:
        pytest.skip(f"prusaslicer: {found.reason}")
    monkeypatch.setenv("XDG_CACHE_HOME", str(tmp_path))
    probe = PRUSASLICER.option_probe
    assert probe is not None
    spec = replace(
        PRUSASLICER,
        option_probe=replace(probe, candidates=lambda listing, baseline: ("extruder",)),
    )
    keys = characterise(spec, "under-test").name_map["extruder"]
    assert len(keys) > 1, f"--extruder mapped to {keys}; fan-out is not representable"


def test_the_engine_separates_a_written_key_from_an_adjusted_one(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """G4's spiral-vase run, against the real engine, as the tracking rule sees it.

    ``--spiral-vase=1`` moves five keys on 2.9.6 and the slice is exactly what
    PrusaSlicer was asked for. Only ``spiral_vase`` follows the value across
    ``=1`` and ``=0``; ``perimeters``, ``fill_density`` and ``top_solid_layers``
    are the engine adjusting the print around a request that never named them.
    Comparing the authored value against those is G4's false red, and it is now
    structurally impossible: they are in ``side_effects``, which is not the map.

    ``perimeters`` is named specifically because it is the case a one-run value
    filter cannot catch -- the constraint sets it to ``1``, which is the sentinel.
    """
    from slicelab.engine.discover import ExitFidelity as Fidelity
    from slicelab.engine.discover import discover

    found = discover(PRUSASLICER)
    if found.fidelity is not Fidelity.ESTABLISHED:
        pytest.skip(f"prusaslicer: {found.reason}")
    monkeypatch.setenv("XDG_CACHE_HOME", str(tmp_path))
    probe = PRUSASLICER.option_probe
    assert probe is not None
    spec = replace(
        PRUSASLICER,
        option_probe=replace(probe, candidates=lambda listing, baseline: ("spiral-vase",)),
    )
    entry = characterise(spec, "under-test").entries["spiral-vase"]
    assert entry.keys == ("spiral_vase",), f"spiral-vase mapped to {entry.keys}"
    assert "perimeters" in entry.side_effects
    assert "fill_density" in entry.side_effects
    assert not set(entry.keys) & set(entry.side_effects)


def test_the_side_effect_separation_depends_on_the_sentinel_pair(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The claim an earlier revision got wrong, pinned against the real engine.

    That docstring said the separation was "structural, with no heuristic". It is
    not: it holds only when some pair carries verbatim. Changing nothing but the
    pair, on the same option and the same build:

    * ``('1', '0')`` -- ``keys=('spiral_vase',)``, four constraints as side
      effects, tracking exact.
    * ``('true', '1')`` -- ``true`` resolves to ``0`` and neither value is
      echoed, so **all five** keys land in ``keys``, tracking inexact, and
      nothing is separated.

    A dependent constraint does move differently under two different values.
    What tells the populations apart is the verbatim echo, not the fact of
    moving -- which is why an inexact entry is a weaker thing than a normalised
    one and a readback has to be told.
    """
    from slicelab.engine.discover import ExitFidelity as Fidelity
    from slicelab.engine.discover import discover

    found = discover(PRUSASLICER)
    if found.fidelity is not Fidelity.ESTABLISHED:
        pytest.skip(f"prusaslicer: {found.reason}")
    monkeypatch.setenv("XDG_CACHE_HOME", str(tmp_path))
    probe = PRUSASLICER.option_probe
    assert probe is not None

    def entry_for(pair: tuple[str, str]) -> MapEntry:
        spec = replace(
            PRUSASLICER,
            option_probe=replace(
                probe,
                sentinels=(pair,),
                candidates=lambda listing, baseline: ("spiral-vase",),
            ),
        )
        return characterise(spec, "under-test").entries["spiral-vase"]

    carried = entry_for(("1", "0"))
    assert carried.tracking is Tracking.EXACT
    assert carried.keys == ("spiral_vase",)
    assert "perimeters" in carried.side_effects

    echoed_by_neither = entry_for(("true", "1"))
    assert echoed_by_neither.tracking is Tracking.INEXACT
    assert "perimeters" in echoed_by_neither.keys, (
        "with no verbatim pair the constraint is not separable, and the entry "
        "must not pretend otherwise"
    )
    assert echoed_by_neither.side_effects == ()


def test_an_option_that_writes_no_configuration_is_not_a_mapping(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """D7 against the real engine: ``--post-process`` exits 0 and writes no ini."""
    from slicelab.engine.discover import ExitFidelity as Fidelity
    from slicelab.engine.discover import discover

    found = discover(PRUSASLICER)
    if found.fidelity is not Fidelity.ESTABLISHED:
        pytest.skip(f"prusaslicer: {found.reason}")
    monkeypatch.setenv("XDG_CACHE_HOME", str(tmp_path))
    probe = PRUSASLICER.option_probe
    assert probe is not None
    spec = replace(
        PRUSASLICER,
        option_probe=replace(
            probe, candidates=lambda listing, baseline: ("post-process", "export-sla")
        ),
    )
    result = characterise(spec, "under-test")
    assert result.outcomes["post-process"] == ProbeOutcome.NO_ARTIFACT.value
    assert result.outcomes["export-sla"] == ProbeOutcome.NAMESPACE_CHANGED.value
    assert result.name_map == {}


def test_the_environment_the_cache_lands_in_is_part_of_the_test(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """No test here may write into the real user's cache.

    ``XDG_CACHE_HOME`` is exactly the ambient value a defect hides behind, so it
    is parametrized rather than inherited -- and this asserts the parametrization
    is the thing being read.
    """
    monkeypatch.setenv("XDG_CACHE_HOME", str(tmp_path))
    assert tmp_path in cache_path_for(PRUSASLICER, "2.9.6").parents
    monkeypatch.delenv("XDG_CACHE_HOME")
    assert os.environ.get("XDG_CACHE_HOME") is None
    assert Path.home() in cache_path_for(PRUSASLICER, "2.9.6").parents
