"""The gates between a run that produced nothing usable and a handed-over artifact.

`slice` promotes a G-code file to a path the author will print from. Six conditions
mean the staged file is not something slicelab can stand behind, whatever it
contains: the engine died on a signal, it ran out of time, it wrote no artifact, it
wrote an empty one, it exited non-zero having written one, or it wrote an artifact
and no configuration to adjudicate it against.

Each is one `if`, and each is the only thing standing between such a run and
`sliced` at exit 0. `tests/test_artifact_gate.py` records that the `resolve`-side
versions of three of these had no red state and that removing any of them left the
whole suite green; the `slice`-side copy shipped with the same defect and a fourth
branch besides. A mutation sweep confirmed it: deleting the zero-size check, the
non-zero-exit check, the signal check, the timeout check or the no-configuration
check each left all 391 tests passing (org contract 2.4).

In-process against a fabricated `Completed`, for the reason that file gives: the
states are not reachable on demand from a real engine. The two that ARE reachable
are measured against one in `tests/test_slice_against_the_engine.py`.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from slicelab.adapters import PRUSASLICER
from slicelab.container import Container, sniff
from slicelab.engine.launch import Completed
from slicelab.resolve import ResolveError, ResolveIncomplete
from slicelab.slicing import _configuration, _gate

SOURCE = Path("slice.toml")


@pytest.fixture
def an_artifact(tmp_path: Path) -> Path:
    """A staged artifact that is present and non-empty: the case the gates survive.

    Every test here would otherwise pass through the "wrote no artifact" branch and
    prove nothing about the branch it names.
    """
    staged = tmp_path / "artifact"
    staged.write_bytes(b"; generated by a slicer\nG1 X0 Y0\n")
    return staged


def test_an_artifact_beside_a_signalled_engine_is_never_handed_over(an_artifact: Path) -> None:
    """A signal carries no cause, so the file it left behind means nothing.

    This pins that the run is refused, not which code it is refused with: D15 says
    signal death is `incomplete` (2) and both verbs exit `4`. That contradiction is
    #41 and is older than this verb, so the assertion here is deliberately about the
    gate rather than about the number, and will not have to be rewritten whichever
    way #41 goes.

    The artifact is written incrementally as the engine works, so a crash at 80%
    leaves a file that opens, parses, and stops in the middle of the object.
    """
    completed = Completed(exit_status=None, signal=11, stdout="", stderr="")
    with pytest.raises(ResolveError, match="died on signal 11"):
        _gate(completed, an_artifact, PRUSASLICER, SOURCE)


def test_an_artifact_beside_a_timed_out_engine_is_never_handed_over(an_artifact: Path) -> None:
    """Same shape, same open question about the code, and plainly reachable: the run
    is under a timeout."""
    completed = Completed(exit_status=None, signal=None, timed_out=True)
    with pytest.raises(ResolveError, match="did not finish slicing"):
        _gate(completed, an_artifact, PRUSASLICER, SOURCE)


def test_a_zero_byte_artifact_is_not_an_artifact(tmp_path: Path) -> None:
    """The engine creates `-o` and then fails, which leaves the file there.

    `is_file()` alone says yes. Without the size, an empty file is handed over as a
    slice at exit 0, and it replaces whatever the author had -- the one outcome the
    staging in D7 exists to make impossible.
    """
    empty = tmp_path / "artifact"
    empty.touch()
    completed = Completed(exit_status=0, signal=None, stdout="", stderr="")
    with pytest.raises(ResolveIncomplete, match="wrote no artifact"):
        _gate(completed, empty, PRUSASLICER, SOURCE)


def test_an_artifact_from_a_non_zero_exit_is_not_evidence(an_artifact: Path) -> None:
    """The file exists and the engine disowned it, so it is not a verdict.

    The opposite direction to [V4], and the reason the gate asks the file *and* the
    status rather than picking whichever one is convenient.
    """
    completed = Completed(exit_status=1, signal=None, stdout="", stderr="slicing failed")
    with pytest.raises(ResolveIncomplete, match="having written an artifact"):
        _gate(completed, an_artifact, PRUSASLICER, SOURCE)


def test_a_good_run_passes_the_gate(an_artifact: Path) -> None:
    """The control. Without it every test above could pass on a gate that refuses
    everything, which is not a gate -- it is a tool that never works."""
    completed = Completed(exit_status=0, signal=None, stdout="", stderr="")
    _gate(completed, an_artifact, PRUSASLICER, SOURCE)


def test_an_artifact_with_no_configuration_cannot_be_adjudicated(tmp_path: Path) -> None:
    """`incomplete`, not `error`. The engine sliced, so something happened; what it resolved that
    intent to is unknowable without the document, and unknowable is `incomplete`."""
    completed = Completed(exit_status=0, signal=None, stdout="", stderr="")
    with pytest.raises(ResolveIncomplete, match="and no configuration"):
        _configuration(completed, tmp_path / "readback", PRUSASLICER, SOURCE)


def test_a_configuration_that_is_there_is_read(tmp_path: Path) -> None:
    """The control for the one above."""
    staged = tmp_path / "readback"
    staged.write_text("perimeters = 4\n", encoding="utf-8")
    completed = Completed(exit_status=0, signal=None, stdout="", stderr="")
    assert _configuration(completed, staged, PRUSASLICER, SOURCE) == "perimeters = 4\n"


def test_an_engine_that_declared_no_magic_leaves_the_container_undetermined(
    tmp_path: Path,
) -> None:
    """D10. No adapter in the tree reaches this -- the only engine that can be asked
    for a slice declares `GCDE` -- so it is pinned here at the unit, where the next
    adapter will meet it. `undetermined` is the honest answer to a question slicelab
    has not measured for that engine, and guessing `gcode` would be a claim about a
    footer a reader is about to go looking for."""
    artifact = tmp_path / "artifact"
    artifact.write_bytes(b"GCDE\x00\x00")
    assert sniff(artifact, None) is Container.UNDETERMINED
    assert sniff(artifact, b"GCDE") is Container.BGCODE
