"""The option-to-key map, and the three ways a probe can measure silence.

``notes/critique.md`` G2 is the reason the map is probed rather than derived, and
the reason it must not be derived is reproduced here as an engine test: on
PrusaSlicer 2.9.6 ``--after-layer-gcode`` writes ``layer_gcode``, and a
dash-to-underscore readback calls that a perfectly applied key ``absent``.

Most of this file needs no engine. The classification rules are where the probe
can silently become wrong -- an engine that writes no artifact at exit 0 would
otherwise read as an option that moved every key at once -- so each of them is
driven against a stand-in and has a red state on every runner, including the ones
with no slicer installed.
"""

from __future__ import annotations

import ast
import json
import os
from collections.abc import Mapping, Sequence
from dataclasses import replace
from pathlib import Path

import pytest

from slicelab.adapters import ORCASLICER, PRUSASLICER, EngineSpec
from slicelab.adapters.orcaslicer import _options_from_settings_keys, _read_settings_json
from slicelab.adapters.prusaslicer import _options_from_help_fff, _read_ini
from slicelab.engine.characterise import (
    Characterisation,
    CharacterisationError,
    ProbeOutcome,
    _cache_root,
    _probe_one,
    _read_cache,
    _safe,
    _write_cache,
    cache_path_for,
    characterise,
    load_name_map,
)
from slicelab.engine.discover import Discovery, ExitFidelity, LaunchForm, LaunchKind, argv_for
from slicelab.engine.launch import Completed, run
from tests.test_names_confined import undeclared_terms

PACKAGE = Path(__file__).resolve().parent.parent / "slicelab"

# -- the adapters' halves: enumerating options, and reading a readback ---------

#: The two line shapes ``--help-fff`` actually uses, reduced to their skeletons.
#: The second is D28's alias line -- the one a leading-option scan misses, and the
#: one that produced G2's false ``absent``.
HELP_SAMPLE = """PrusaSlicer-2.9.6 based on Slic3r

Actions:
 --export-sla, --sla Slice the model and export SLA printing layers as PNG.
 --help, -h          Show this help.

Options:
 --after-layer-gcode ABCD, --layer-gcode ABCD
                     Custom G-code per layer.
 --bed-shape         (default: 0x0,200x0,200x200,0x200)
 --perimeters N      How many perimeters.
Note: a prose line that mentions --perimeters must not become an option.
"""


def test_the_help_parser_reads_past_the_first_name_on_a_line() -> None:
    """Aliases are the population the collision search has to be exhaustive over."""
    found = _options_from_help_fff(HELP_SAMPLE, {})
    assert found == (
        "export-sla",
        "sla",
        "help",
        "after-layer-gcode",
        "layer-gcode",
        "bed-shape",
        "perimeters",
    )


def test_the_help_parser_stops_at_the_description() -> None:
    """A description is not a spelling, whatever punctuation it contains.

    ``--export-sla, --sla Slice the model...`` puts the description on the same
    line as the second spelling, so reading every comma-separated group would
    harvest sentences as option names.
    """
    assert "slice" not in _options_from_help_fff(HELP_SAMPLE, {})
    assert not any(" " in name for name in _options_from_help_fff(HELP_SAMPLE, {}))


def test_the_help_parser_ignores_prose_that_names_an_option() -> None:
    """Only a line that *starts* with an option is an option line."""
    assert _options_from_help_fff("Config keys such as --fill-pattern=stars.\n", {}) == ()


def test_the_ini_reader_takes_values_verbatim() -> None:
    """A resolved G-code block has to survive the round trip unaltered.

    The readback compares requested against resolved for equality, so a reader
    that strips or normalises is deciding a key was applied on evidence it
    changed itself.
    """
    parsed = _read_ini(
        "# generated by PrusaSlicer\n"
        "[print:x]\n"
        "layer_gcode = ;LAYER {layer_num}\\nM117 hi \n"
        "perimeters = 3\n"
        "notes = \n"
    )
    assert parsed == {
        "layer_gcode": ";LAYER {layer_num}\\nM117 hi ",
        "perimeters": "3",
        "notes": "",
    }


def test_the_settings_reader_keeps_a_list_distinguishable_from_a_string() -> None:
    """``["1", "0"]`` and ``"1,0"`` are different states and must stay different."""
    parsed = _read_settings_json('{"a": "2", "b": ["1", "0"], "c": ["1,0"]}')
    assert parsed["a"] == "2"
    assert parsed["b"] != parsed["c"]


def test_orca_candidates_come_from_the_keys_because_orca_lists_no_options() -> None:
    assert _options_from_settings_keys("", {"wall_loops": "2", "a_b_c": "1"}) == (
        "a-b-c",
        "wall-loops",
    )


# -- the driver's classification rules, against a stand-in engine --------------

FORM = LaunchForm(LaunchKind.PATH, ["/nonexistent/engine"], "a stand-in")
FOUND = Discovery(engine="stand-in", form=FORM, fidelity=ExitFidelity.ESTABLISHED, reason="test")
BASELINE: Mapping[str, str] = {"alpha": "1", "beta": "2", "gamma": "3"}


class FakeEngine:
    """An engine that writes whatever the test says, and records nothing else."""

    def __init__(self, sidecar: Path, script: Sequence[tuple[int, str, str | None]]) -> None:
        self.sidecar = sidecar
        self.script = list(script)
        self.calls = 0

    def __call__(self, argv: list[str], *, timeout: float = 0.0) -> Completed:
        status, said, writes = self.script[min(self.calls, len(self.script) - 1)]
        self.calls += 1
        if writes is not None:
            self.sidecar.write_text(writes, encoding="utf-8")
        if status < 0:
            return Completed(argv=argv, exit_status=None, signal=None, timed_out=True)
        return Completed(argv=argv, exit_status=status, stderr=said)


def _ini(pairs: Mapping[str, str]) -> str:
    return "".join(f"{k} = {v}\n" for k, v in pairs.items())


def _probe(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    script: Sequence[tuple[int, str, str | None]],
    *,
    volatile: tuple[str, ...] = (),
) -> tuple[ProbeOutcome, tuple[str, ...], FakeEngine]:
    sidecar = tmp_path / "readback"
    engine = FakeEngine(sidecar, script)
    monkeypatch.setattr("slicelab.engine.characterise.run", engine)
    probe = PRUSASLICER.option_probe
    assert probe is not None
    outcome, keys = _probe_one(
        PRUSASLICER, FOUND, probe, "an-option", sidecar, BASELINE, volatile, timeout=1.0
    )
    return outcome, keys, engine


def test_a_key_that_moved_is_the_mapping(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    outcome, keys, _ = _probe(tmp_path, monkeypatch, [(0, "", _ini({**BASELINE, "beta": "moved"}))])
    assert (outcome, keys) == (ProbeOutcome.MAPPED, ("beta",))


def test_several_keys_moving_is_recorded_as_several(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Fan-out is real: ``--extruder`` writes three keys on 2.9.6.

    A mapping that kept one of them would let a readback report ``applied`` with
    two keys never looked at -- green over an intent only partly honoured.
    """
    outcome, keys, _ = _probe(
        tmp_path,
        monkeypatch,
        [(0, "", _ini({**BASELINE, "alpha": "x", "gamma": "y"}))],
    )
    assert (outcome, keys) == (ProbeOutcome.MAPPED, ("alpha", "gamma"))


def test_a_key_is_mapped_on_having_moved_and_not_on_matching_the_sentinel(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The filter that looks obvious, refused on evidence.

    Keeping only the keys whose resolved value equals the sentinel verbatim would
    look like a way to tell a real write from a dependent constraint. Measured
    against 2.9.6 it **unmaps 89 of the 330 mapped options**, because the engine
    normalises legitimately: ``--filament-shrinkage-compensation-xy=7`` resolves
    to ``7%``, ``--draft-shield=1`` to ``enabled``, and a string sentinel to ``0``
    on every numeric option. It also fails at the job it was for -- the
    spiral-vase constraint sets ``perimeters`` to exactly the sentinel.

    So the rule is that the key moved, and the sentinel's own value is not
    consulted.
    """
    outcome, keys, _ = _probe(
        tmp_path, monkeypatch, [(0, "", _ini({**BASELINE, "beta": "normalised-elsewhere"}))]
    )
    assert (outcome, keys) == (ProbeOutcome.MAPPED, ("beta",))


def test_a_new_key_is_a_mapping_and_not_a_namespace_change(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """``--bed-custom-texture`` adds a key the default dump does not have."""
    outcome, keys, _ = _probe(tmp_path, monkeypatch, [(0, "", _ini({**BASELINE, "delta": "new"}))])
    assert (outcome, keys) == (ProbeOutcome.MAPPED, ("delta",))


def test_a_dump_that_lost_baseline_keys_is_a_mode_switch(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """``--export-sla`` swaps the whole key namespace; that is not a mapping.

    Measured on 2.9.6: it drops 334 of the 343 baseline keys and adds 143 of its
    own. Reading the difference as "this option writes 480 keys" is the shape the
    prototype produced, and no count threshold is needed to refuse it -- a config
    option never removes a key.
    """
    outcome, keys, _ = _probe(tmp_path, monkeypatch, [(0, "", _ini({"sla_only": "1"}))])
    assert (outcome, keys) == (ProbeOutcome.NAMESPACE_CHANGED, ())


def test_exit_zero_with_no_artifact_is_not_a_mapping(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """D7, aimed at the probe. ``--post-process`` and ``--info`` do exactly this.

    Without the gate the absent file parses to ``{}``, every baseline key reads as
    moved, and one option is recorded as writing all 343.
    """
    outcome, keys, _ = _probe(tmp_path, monkeypatch, [(0, "", None)])
    assert (outcome, keys) == (ProbeOutcome.NO_ARTIFACT, ())


def test_an_empty_artifact_counts_as_no_artifact(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Zero bytes parse to zero keys, which is the same false fan-out."""
    outcome, _, _ = _probe(tmp_path, monkeypatch, [(0, "", "")])
    assert outcome is ProbeOutcome.NO_ARTIFACT


def test_an_engine_that_never_returns_is_not_an_engine_that_refused(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """``--gcodeviewer`` opens a window and waits. It must cost one timeout, once."""
    outcome, _, engine = _probe(tmp_path, monkeypatch, [(-1, "", None)])
    assert outcome is ProbeOutcome.TIMED_OUT
    assert engine.calls == 1, "a hang must not be retried once per sentinel"


def test_an_option_the_engine_does_not_have_stops_at_the_first_sentinel(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    outcome, _, engine = _probe(tmp_path, monkeypatch, [(1, "Unknown option --an-option", None)])
    assert outcome is ProbeOutcome.UNKNOWN_OPTION
    assert engine.calls == 1


def test_a_bad_value_costs_a_sentinel_and_not_the_option(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Options are typed: a rejection is "wrong value", not "no such option"."""
    probe = PRUSASLICER.option_probe
    assert probe is not None
    outcome, keys, engine = _probe(
        tmp_path,
        monkeypatch,
        [
            (1, "Invalid value supplied", None),
            (0, "", _ini({**BASELINE, "beta": "7"})),
        ],
    )
    assert (outcome, keys) == (ProbeOutcome.MAPPED, ("beta",))
    assert engine.calls == 2


def test_every_sentinel_refused_is_a_could_not_tell(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    probe = PRUSASLICER.option_probe
    assert probe is not None
    outcome, keys, engine = _probe(tmp_path, monkeypatch, [(1, "Invalid value supplied", None)])
    assert (outcome, keys) == (ProbeOutcome.REJECTED, ())
    assert engine.calls == len(probe.sentinels)


def test_an_accepted_option_that_moved_nothing_is_not_in_the_map(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """And only after every sentinel has been tried, not the first."""
    probe = PRUSASLICER.option_probe
    assert probe is not None
    outcome, keys, engine = _probe(tmp_path, monkeypatch, [(0, "", _ini(BASELINE))])
    assert (outcome, keys) == (ProbeOutcome.NO_KEY_MOVED, ())
    assert engine.calls == len(probe.sentinels)


def test_a_sentinel_that_resolves_to_the_default_is_not_an_answer(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The defect this probe shipped for one measurement, as a regression test.

    D5: PrusaSlicer's boolean options validate nothing, and anything that is not
    literally ``1`` resolves to ``0``. ``--spiral-vase=SLICELABPROBE`` therefore
    exits 0, resolves to the ``0`` already in the dump, and moves no key. Stopping
    at the first accepted sentinel classified 110 real options -- ``--spiral-vase``,
    ``--support-material`` and ``--thin-walls`` among them -- as writing no
    configuration, which is the opposite of the truth and would keep every one of
    them out of the map.
    """
    outcome, keys, engine = _probe(
        tmp_path,
        monkeypatch,
        [
            (0, "", _ini(BASELINE)),
            (0, "", _ini({**BASELINE, "beta": "1"})),
        ],
    )
    assert (outcome, keys) == (ProbeOutcome.MAPPED, ("beta",))
    assert engine.calls == 2


def test_a_key_that_will_not_hold_still_is_not_attributed_to_the_option(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A key that differs between two identical baselines differs under every option.

    Left in, it would put a plausible extra key on every entry in the map. D8's
    habit -- reproducibility is measured, never assumed -- applied to the thing
    the whole map is diffed against.
    """
    outcome, keys, _ = _probe(
        tmp_path,
        monkeypatch,
        [(0, "", _ini({**BASELINE, "alpha": "clock", "beta": "real"}))],
        volatile=("alpha",),
    )
    assert (outcome, keys) == (ProbeOutcome.MAPPED, ("beta",))


# -- the cache: what it is keyed by, and what it refuses to believe -----------


def test_the_cache_is_keyed_by_engine_and_by_version(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The map is a per-build fact, so one engine's two builds are two files.

    A map carried across a release is confidently wrong in exactly the direction
    this project refuses: options are renamed and keys are added between versions,
    and nothing would report the gap.
    """
    monkeypatch.setenv("XDG_CACHE_HOME", str(tmp_path))
    here = cache_path_for(PRUSASLICER, "2.9.6")
    later = cache_path_for(PRUSASLICER, "2.10.0")
    other = cache_path_for(ORCASLICER, "2.9.6")
    assert here != later != other and here != other
    assert tmp_path in here.parents
    assert PRUSASLICER.name in here.parts and "2.9.6" in here.parts


def test_a_relative_cache_home_is_ignored(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """The basedir spec says a relative value MUST be ignored.

    Honouring one scatters a cache directory wherever the user was standing, which
    is the defect ``launch._scratch_roots`` was written about.
    """
    monkeypatch.setenv("XDG_CACHE_HOME", "relative-cache")
    monkeypatch.chdir(tmp_path)
    assert Path.home() in _cache_root().parents


@pytest.mark.parametrize(
    ("version", "expected"),
    [
        ("2.9.6", "2.9.6"),
        # A real one. `Identity` reads this off the Flathub build's own banner, and
        # `+` and `.` have to survive or two builds share one cache entry.
        ("2.9.6+flathub.org", "2.9.6+flathub.org"),
    ],
)
def test_a_real_version_reaches_the_cache_path_intact(version: str, expected: str) -> None:
    assert _safe(version) == expected


@pytest.mark.parametrize("version", ["../../etc", "a/b", "...", "   ", "", ".", "..", "a\0b"])
def test_a_version_can_never_climb_out_of_the_cache_directory(version: str) -> None:
    """A build states its own version and slicelab does not get to assume what is in it.

    Asserted as the property rather than as an expected string: what matters is
    that the result is one path segment which is neither empty nor a traversal,
    not which character each rejected one became.
    """
    safe = _safe(version)
    assert safe and safe not in (".", "..")
    assert Path(safe).parts == (safe,)


def test_the_cache_round_trips_tuples_rather_than_lists(tmp_path: Path) -> None:
    result = Characterisation(
        engine="e",
        version="1",
        name_map={"extruder": ("infill_extruder", "perimeter_extruder")},
        outcomes={"extruder": "mapped", "info": "no-artifact"},
        baseline_key_count=343,
        volatile_keys=(),
    )
    path = tmp_path / "m.json"
    _write_cache(path, result)
    assert _read_cache(path) == {"extruder": ("infill_extruder", "perimeter_extruder")}


def test_the_cache_records_why_an_option_is_not_in_the_map(tmp_path: Path) -> None:
    """An unmapped option must be a fact with a cause, not an absence.

    That is what lets a caller refuse it at 64 -- slicelab's own argv is wrong --
    rather than reporting it as ``absent``, which is a claim about the engine.
    """
    path = tmp_path / "m.json"
    _write_cache(
        path,
        Characterisation("e", "1", {"a": ("a",)}, {"a": "mapped", "b": "no-key-moved"}, 1, ()),
    )
    document = json.loads(path.read_text(encoding="utf-8"))
    assert document["outcomes"]["b"] == "no-key-moved"


@pytest.mark.parametrize(
    "content",
    [
        "not json at all",
        '{"schema": 999, "map": {"a": ["b"]}}',
        '{"schema": 1, "map": {}}',
        '{"schema": 1, "map": {"a": "b"}}',
        '{"schema": 1}',
        "[]",
    ],
)
def test_a_cache_that_is_not_the_shape_we_wrote_is_a_miss(tmp_path: Path, content: str) -> None:
    """Re-measure rather than adapt. The engine is the authority; this is a receipt.

    An empty map is refused too: it is indistinguishable from a probe that reached
    nothing, and returning it would make every option read as unmapped.
    """
    path = tmp_path / "m.json"
    path.write_text(content, encoding="utf-8")
    assert _read_cache(path) is None


def test_a_missing_cache_is_a_miss(tmp_path: Path) -> None:
    assert _read_cache(tmp_path / "nothing.json") is None


def test_a_cached_map_is_returned_without_touching_the_engine(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("XDG_CACHE_HOME", str(tmp_path))
    _write_cache(
        cache_path_for(PRUSASLICER, "2.9.6"),
        Characterisation(
            "prusaslicer", "2.9.6", {"after-layer-gcode": ("layer_gcode",)}, {}, 1, ()
        ),
    )

    def refuse(*args: object, **kwargs: object) -> Characterisation:
        raise AssertionError("a cache hit must not reach the engine")

    monkeypatch.setattr("slicelab.engine.characterise.characterise", refuse)
    assert load_name_map(PRUSASLICER, "2.9.6") == {"after-layer-gcode": ("layer_gcode",)}


def test_a_build_that_will_not_state_its_version_is_refused(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """``Identity.exact`` is False here, and caching under "" would poison the next build."""
    with pytest.raises(CharacterisationError, match="per-build"):
        load_name_map(PRUSASLICER, "  ")


def test_an_engine_with_no_probe_is_refused_rather_than_guessed_at() -> None:
    """The alternative to refusing is the transform G2 reproduced a false absent from."""
    with pytest.raises(CharacterisationError, match="transform"):
        characterise(replace(PRUSASLICER, option_probe=None), "2.9.6")


def test_an_engine_with_no_readback_is_refused() -> None:
    with pytest.raises(CharacterisationError, match="dump"):
        characterise(replace(PRUSASLICER, readback_flag=None), "2.9.6")


# -- the boundary: the driver must stay ignorant of every engine ---------------


def _imported_modules(path: Path) -> set[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    names: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            names.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module and node.level == 0:
            names.add(node.module)
    return names


def test_the_probe_driver_imports_no_adapter_module() -> None:
    """It may know that engines exist. It may not know which one it is driving.

    ``slicelab.adapters`` is the facade holding ``EngineSpec`` and ``OptionProbe``;
    reaching past it to ``slicelab.adapters.prusaslicer`` is how ``--help-fff``
    parsing would arrive in the core, one convenience at a time.
    """
    imported = _imported_modules(PACKAGE / "engine" / "characterise.py")
    reached = sorted(m for m in imported if m.startswith("slicelab.adapters."))
    assert reached == [], f"the probe driver reached into an adapter: {reached}"


def test_the_import_boundary_test_is_not_vacuous() -> None:
    """The adapter modules must be reachable, or the check above finds nothing."""
    imported = _imported_modules(PACKAGE / "adapters" / "__init__.py")
    assert any(m.startswith("slicelab.adapters.") for m in imported)


# -- against a real engine -----------------------------------------------------


def _live_vocabulary(spec: EngineSpec, tmp_path: Path) -> tuple[tuple[str, ...], Mapping[str, str]]:
    """This build's own option names and config keys, read from the engine."""
    from slicelab.engine.discover import discover

    probe = spec.option_probe
    assert probe is not None and spec.readback_flag is not None
    found = discover(spec)
    if found.form is None:
        pytest.skip(f"{spec.name}: {found.reason}")
    sidecar = tmp_path / "readback"
    run(argv_for(found.form, (f"{spec.readback_flag}={sidecar}",), (str(sidecar),)), timeout=90.0)
    if not sidecar.exists() or sidecar.stat().st_size == 0:
        pytest.skip(f"{spec.name} wrote no readback for a request with nothing set")
    baseline = probe.read_config(sidecar.read_text(encoding="utf-8", errors="replace"))
    listing = ""
    if probe.enumerate_argv:
        completed = run(argv_for(found.form, probe.enumerate_argv, ()), timeout=90.0)
        listing = completed.stdout + completed.stderr
    return probe.candidates(listing, baseline), baseline


def _scanned_sources() -> list[Path]:
    """Every module outside ``adapters/``. The claim is about all of them."""
    adapters = PACKAGE / "adapters"
    return [p for p in sorted(PACKAGE.rglob("*.py")) if adapters not in p.parents]


def test_no_live_engine_key_or_option_appears_outside_the_adapters(
    any_engine: EngineSpec, tmp_path: Path
) -> None:
    """D26's claim, measured against the vocabulary the engine states today.

    ``tests/test_names_confined.py`` scans the modules directly under
    ``slicelab/``; ``slicelab/engine/`` is not among them, and the probe driver
    lives there. Rather than widen that decision's whitelist -- the dumping ground
    its supersede clause warns about -- the same claim is made the expensive way:
    read this build's own config keys, and require that not one of them survives
    ``undeclared_terms`` anywhere outside ``slicelab/adapters/``.

    Reusing that function rather than scanning words is not incidental. A blanket
    "no engine word anywhere" scan is red on day one, because ``output``,
    ``load``, ``save`` and ``info`` are engine option names and ordinary English
    at the same time -- measured against this corpus, a word scan flags 54 terms
    across eleven clean modules, nearly all of them prose. D26 settled that
    already: a literal is either prose or vocabulary, and prose is not a leak.

    Scoped to the **config-key namespace**, which is D26's own scope rather than a
    convenient narrowing. The option names are the map's keys and the config keys
    are its values, and only the values are what a readback compares against.
    Putting the option names back costs exactly one false positive, worth naming
    because it is the shape of the whole problem: ``engine/identity.py`` runs
    ``flatpak info`` to read a deployment commit, and ``--info`` is also a
    PrusaSlicer option, so the literal ``"info"`` there is a Flatpak subcommand
    colliding with an engine option and not a leak of anything.
    """
    _options, baseline = _live_vocabulary(any_engine, tmp_path)
    vocabulary = set(baseline)
    assert len(vocabulary) > 200, (
        f"{any_engine.name} stated {len(vocabulary)} keys; it was not read"
    )

    offenders: list[str] = []
    for path in _scanned_sources():
        terms = set(undeclared_terms(path.read_text(encoding="utf-8"), str(path)))
        for term in sorted(vocabulary & terms):
            offenders.append(f"{path.relative_to(PACKAGE)} names {term!r}")
    assert offenders == [], (
        "an engine's own vocabulary reached a literal outside slicelab/adapters/: "
        + "; ".join(offenders)
    )


def test_the_live_vocabulary_check_can_go_red(any_engine: EngineSpec, tmp_path: Path) -> None:
    """A guard on the guard: the scan must catch a term that really is in the corpus."""
    options, baseline = _live_vocabulary(any_engine, tmp_path)
    assert options and baseline
    sample = sorted(baseline)[0]
    assert sample in set(undeclared_terms(f'def f(rb):\n    return rb["{sample}"]\n'))


def test_the_engine_writes_a_key_the_options_name_does_not_predict(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """G2's reproduction, as a test rather than a paragraph.

    ``--after-layer-gcode`` writes ``layer_gcode``. A dash-to-underscore readback
    looks for ``after_layer_gcode``, does not find it, and reports ``absent`` on a
    key the engine applied exactly -- forcing exit 2 on a correct run.
    """
    from slicelab.engine.discover import ExitFidelity as Fidelity
    from slicelab.engine.discover import discover

    found = discover(PRUSASLICER)
    if found.fidelity is not Fidelity.ESTABLISHED:
        pytest.skip(f"prusaslicer: {found.reason}")
    monkeypatch.setenv("XDG_CACHE_HOME", str(tmp_path))
    probe = PRUSASLICER.option_probe
    assert probe is not None
    spec = replace(
        PRUSASLICER,
        option_probe=replace(probe, candidates=lambda listing, baseline: ("after-layer-gcode",)),
    )
    result = characterise(spec, "under-test")
    assert result.name_map["after-layer-gcode"] == ("layer_gcode",)


def test_one_option_can_write_several_keys(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """``--extruder`` writes three. A ``str`` value would have to drop two of them."""
    from slicelab.engine.discover import ExitFidelity as Fidelity
    from slicelab.engine.discover import discover

    found = discover(PRUSASLICER)
    if found.fidelity is not Fidelity.ESTABLISHED:
        pytest.skip(f"prusaslicer: {found.reason}")
    monkeypatch.setenv("XDG_CACHE_HOME", str(tmp_path))
    probe = PRUSASLICER.option_probe
    assert probe is not None
    spec = replace(
        PRUSASLICER,
        option_probe=replace(probe, candidates=lambda listing, baseline: ("extruder",)),
    )
    keys = characterise(spec, "under-test").name_map["extruder"]
    assert len(keys) > 1, f"--extruder mapped to {keys}; fan-out is not representable"


def test_an_option_that_writes_no_configuration_is_not_a_mapping(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """D7 against the real engine: ``--post-process`` exits 0 and writes no ini."""
    from slicelab.engine.discover import ExitFidelity as Fidelity
    from slicelab.engine.discover import discover

    found = discover(PRUSASLICER)
    if found.fidelity is not Fidelity.ESTABLISHED:
        pytest.skip(f"prusaslicer: {found.reason}")
    monkeypatch.setenv("XDG_CACHE_HOME", str(tmp_path))
    probe = PRUSASLICER.option_probe
    assert probe is not None
    spec = replace(
        PRUSASLICER,
        option_probe=replace(
            probe, candidates=lambda listing, baseline: ("post-process", "export-sla")
        ),
    )
    result = characterise(spec, "under-test")
    assert result.outcomes["post-process"] == ProbeOutcome.NO_ARTIFACT.value
    assert result.outcomes["export-sla"] == ProbeOutcome.NAMESPACE_CHANGED.value
    assert result.name_map == {}


def test_the_environment_the_cache_lands_in_is_part_of_the_test(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """No test here may write into the real user's cache.

    ``XDG_CACHE_HOME`` is exactly the ambient value a defect hides behind, so it
    is parametrized rather than inherited -- and this asserts the parametrization
    is the thing being read.
    """
    monkeypatch.setenv("XDG_CACHE_HOME", str(tmp_path))
    assert tmp_path in cache_path_for(PRUSASLICER, "2.9.6").parents
    monkeypatch.delenv("XDG_CACHE_HOME")
    assert os.environ.get("XDG_CACHE_HOME") is None
    assert Path.home() in cache_path_for(PRUSASLICER, "2.9.6").parents
