"""What happens to the artifact when the run does not finish cleanly.

`slice_intent` runs the engine into a scratch directory and, if it will not hand
the result over, keeps that directory so the author can look at the file the engine
actually produced (D7). The decision is one flag and one `except`, and a mutation
sweep found the whole of it inert: narrowing the `except`, dropping the guard that
checks an artifact exists, and removing the path from the report each left all 416
tests green. Nothing called `slice_intent` in process, and no engine-backed test
reaches those lines -- [V4] and [V15] produce no artifact, and the coerced case
returns normally.

So these drive `slice_intent` directly with the engine stubbed out. That is the
only way to reach a fault raised *after* a good artifact exists, which is the state
the whole clause is about: `redact` refusing an unmeasured secret key, `sniff`
failing to open a file, `promote` unable to write. Each of those deleted the
artifact before this file existed.
"""

from __future__ import annotations

import os
import shutil
from pathlib import Path

import pytest

import slicelab.slicing as slicing
from slicelab.engine.characterise import MapEntry, ProbeOutcome, Tracking
from slicelab.engine.discover import Discovery, ExitFidelity, LaunchForm, LaunchKind
from slicelab.engine.launch import Completed
from slicelab.redact import RedactionError
from slicelab.resolve import ResolveError, ResolveIncomplete
from slicelab.slicing import slice_intent, withheld_by

TRIPLE = """[prusaslicer.base]
printer-profile = "Original Prusa i3 MK3S & MK3S+"
print-profile = "0.20mm QUALITY @MK3"
material-profile = "Prusament PLA"
"""

READBACK = "perimeters = 4\nlayer_height = 0.2\n"


@pytest.fixture
def intent(tmp_path: Path) -> Path:
    (tmp_path / "part.stl").write_text("solid cube\nendsolid cube\n", encoding="utf-8")
    path = tmp_path / "slice.toml"
    path.write_text(
        '[geometry]\nmodel = "part.stl"\n\n[output]\ngcode = "part.gcode"\n\n'
        + TRIPLE
        + "\n[prusaslicer.set]\nperimeters = 4\n",
        encoding="utf-8",
    )
    return path


@pytest.fixture
def engine_that_writes(monkeypatch: pytest.MonkeyPatch):
    """A stubbed engine that produces a good artifact and a matching configuration.

    Everything downstream of the run is real: the gate, the redaction, the diff, the
    container sniff and the promotion all see a file that is genuinely there.
    """
    form = LaunchForm(kind=LaunchKind.PATH, argv_prefix=["prusa-slicer"], description="stub")
    monkeypatch.setattr(
        slicing,
        "discover",
        lambda spec: Discovery(
            engine=spec.name, form=form, fidelity=ExitFidelity.ESTABLISHED, reason=""
        ),
    )
    monkeypatch.setattr(
        slicing, "configuration_state", lambda spec, found: slicing.ConfigState.PRESENT
    )
    mapped = MapEntry(
        keys=("perimeters",),
        side_effects=(),
        tracking=Tracking.EXACT,
        outcome=ProbeOutcome.MAPPED,
    )
    monkeypatch.setattr(slicing, "_name_map", lambda spec, found: {"perimeters": mapped})

    written: dict[str, Path] = {}

    def fake_run(argv, capture=()):
        # The staged paths are in the argv the adapter composed, which is also the
        # only place the engine would have found them.
        artifact = Path(argv[argv.index("-o") + 1])
        readback = Path(next(a for a in argv if a.startswith("--save=")).split("=", 1)[1])
        artifact.write_bytes(b"; generated by a slicer\nG1 X0 Y0\n")
        readback.write_text(READBACK, encoding="utf-8")
        written["artifact"] = artifact
        return Completed(exit_status=0, signal=None, stdout="", stderr="")

    monkeypatch.setattr(slicing, "run", fake_run)
    return written


def _discard(fault: BaseException) -> None:
    """Remove a scratch directory a test deliberately provoked slicelab into keeping.

    `tmp_path` does not reach it: it outlives the run by design (D7). Measured before
    this existed -- three directories left behind per suite run, which is the subject
    of `tests/test_stray_files.py` arriving from slicelab's own tests.
    """
    staged = withheld_by(fault)
    if staged is not None:
        shutil.rmtree(staged.parent, ignore_errors=True)


def test_a_clean_run_hands_over_and_leaves_no_scratch(intent: Path, engine_that_writes) -> None:
    """The control. Without it every test below passes on an implementation that
    keeps every scratch directory it ever makes."""
    done = slice_intent(intent)

    assert done.artifact == (intent.parent / "part.gcode").resolve()
    assert done.withheld is None
    assert not engine_that_writes["artifact"].exists(), "the scratch outlived a clean run"


def test_a_fault_after_a_good_artifact_keeps_it_and_names_it(
    intent: Path, engine_that_writes, monkeypatch: pytest.MonkeyPatch
) -> None:
    """`redact` refuses on an unmeasured secret key, which is a real refusal that
    happens after the engine has produced a perfectly good file.

    Before this, the artifact was deleted: the clause caught two exception classes
    and this is a third, so the `finally` ran with nothing kept and the author was
    told neither that a file had existed nor where it went.
    """
    monkeypatch.setattr(
        slicing,
        "redact",
        lambda text, spec: (_ for _ in ()).throw(RedactionError("no measurement")),
    )

    with pytest.raises(RedactionError) as raised:
        slice_intent(intent)

    staged = withheld_by(raised.value)
    assert staged is not None, "the artifact was destroyed by a fault it did not cause"
    assert staged.read_bytes().startswith(b"; generated by")
    _discard(raised.value)


def test_a_fault_from_an_unexpected_class_keeps_the_artifact(
    intent: Path, engine_that_writes, monkeypatch: pytest.MonkeyPatch
) -> None:
    """`sniff` opens a file with no guard, so an `OSError` here is not hypothetical.

    Named separately from the one above because they died for different reasons: that
    one was a class the clause did not list, this one is a class nobody would think
    to list. The rule is the fault's provenance, not its type.
    """
    monkeypatch.setattr(
        slicing, "sniff", lambda artifact, magic: (_ for _ in ()).throw(OSError("device is busy"))
    )

    with pytest.raises(OSError) as raised:
        slice_intent(intent)

    assert withheld_by(raised.value) is not None
    _discard(raised.value)


@pytest.mark.parametrize("payload", [None, b""], ids=["no file", "zero bytes"])
def test_a_run_that_produced_no_artifact_keeps_nothing_and_names_nothing(
    intent: Path, engine_that_writes, monkeypatch: pytest.MonkeyPatch, payload: bytes | None
) -> None:
    """[V4]'s shape. The report must not name a path, because there is no file at it
    -- and the scratch must go, because a directory kept per failed run that nobody
    is told about is litter rather than evidence.

    Twice, because the engine creates `-o` before it has anything to put in it, and a
    zero-byte file is the shape a run that failed immediately leaves. The gate and the
    withholding clause once disagreed on it: one report said the engine wrote no
    artifact and then named the empty one it had kept. With `is_file()` alone in the
    clause, the no-file case is green and the zero-byte case is exactly that report.
    """
    scratches: list[Path] = []

    def wrote_nothing(argv, capture=()):
        artifact = Path(argv[argv.index("-o") + 1])
        scratches.append(artifact.parent)
        if payload is not None:
            artifact.write_bytes(payload)
        return Completed(exit_status=0, signal=None, stdout="", stderr="outside the print volume")

    monkeypatch.setattr(slicing, "run", wrote_nothing)

    with pytest.raises(ResolveIncomplete) as raised:
        slice_intent(intent)

    assert withheld_by(raised.value) is None, "a report named an artifact that was never written"
    assert scratches, "the engine was never reached"
    assert not scratches[0].exists(), "a scratch directory nobody was told about survived"


@pytest.mark.skipif(os.name == "nt", reason="chmod cannot make a directory unwritable on Windows")
def test_a_failure_to_write_the_artifact_keeps_the_one_it_could_not_write(
    tmp_path: Path, engine_that_writes
) -> None:
    """Every destination knowably bad at plan time is refused there, so what reaches
    `promote` is a path that went wrong afterwards -- a directory that lost its write
    bit, a full filesystem, a race. The slice is still a good one, and making the
    author run it again to see it is the cost this clause exists to avoid.

    The output goes in a directory of its own. With everything in one directory the
    readback promotion failed first and this branch never ran, while the test passed
    on the exception raised one step earlier -- the assertion was true and about
    something else.
    """
    (tmp_path / "part.stl").write_text("solid cube\nendsolid cube\n", encoding="utf-8")
    (tmp_path / "out").mkdir()
    intent = tmp_path / "slice.toml"
    intent.write_text(
        '[geometry]\nmodel = "part.stl"\n\n[output]\ngcode = "out/part.gcode"\n\n'
        + TRIPLE
        + "\n[prusaslicer.set]\nperimeters = 4\n",
        encoding="utf-8",
    )
    (tmp_path / "out").chmod(0o500)
    try:
        with pytest.raises(ResolveError, match="cannot write the artifact") as raised:
            slice_intent(intent)
    finally:
        (tmp_path / "out").chmod(0o700)

    assert withheld_by(raised.value) is not None
    assert (tmp_path / "slice.readback.ini").is_file(), "the readback goes first (D31)"
    _discard(raised.value)


def test_a_readback_that_cannot_be_written_hands_over_nothing(
    tmp_path: Path, engine_that_writes
) -> None:
    """D31's ordering, which nothing pinned: moving `_promote_readback` after the
    artifact promotion left all 426 tests green.

    The readback destination is derived from the intent's name and is not one of the
    six things `plan_slice` refuses, so a directory standing there is reachable. With
    the readback second, this run exits 4 having already replaced the author's
    G-code -- which makes `slice`'s own "a non-zero means nothing was handed over"
    false in the case it most needs to be true.
    """
    (tmp_path / "part.stl").write_text("solid cube\nendsolid cube\n", encoding="utf-8")
    intent = tmp_path / "slice.toml"
    intent.write_text(
        '[geometry]\nmodel = "part.stl"\n\n[output]\ngcode = "part.gcode"\n\n'
        + TRIPLE
        + "\n[prusaslicer.set]\nperimeters = 4\n",
        encoding="utf-8",
    )
    (tmp_path / "part.gcode").write_text("PREVIOUS-ARTIFACT\n", encoding="utf-8")
    (tmp_path / "slice.readback.ini").mkdir()

    with pytest.raises(ResolveError) as raised:
        slice_intent(intent)

    assert (tmp_path / "part.gcode").read_text(encoding="utf-8") == "PREVIOUS-ARTIFACT\n", (
        "a run that exited non-zero had already handed over the artifact"
    )
    _discard(raised.value)
