"""What happens to the artifact when the run does not finish cleanly.

`slice_intent` runs the engine into a scratch directory and, if it will not hand
the result over, keeps that directory so the author can look at the file the engine
actually produced (D7). The decision is one flag and one `except`, and a mutation
sweep found the whole of it inert: narrowing the `except`, dropping the guard that
checks an artifact exists, and removing the path from the report each left all 416
tests green. Nothing called `slice_intent` in process, and no engine-backed test
reaches those lines -- [V4] and [V15] produce no artifact, and the coerced case
returns normally.

So these drive `slice_intent` directly with the engine stubbed out. That is the
only way to reach a fault raised *after* a good artifact exists, which is the state
the whole clause is about: `redact` refusing an unmeasured secret key, `sniff`
failing to open a file, `promote` unable to write. Each of those deleted the
artifact before this file existed.
"""

from __future__ import annotations

import hashlib
import os
import shutil
import tempfile
import tomllib
from pathlib import Path

import pytest

import slicelab.slicing as slicing
from slicelab.container import Container
from slicelab.engine.characterise import MapEntry, ProbeOutcome, Tracking
from slicelab.engine.discover import Discovery, ExitFidelity, LaunchForm, LaunchKind
from slicelab.engine.identity import Identity
from slicelab.engine.launch import Completed
from slicelab.redact import RedactionError
from slicelab.resolve import ResolveError, ResolveIncomplete
from slicelab.slicing import slice_intent, withheld_by
from slicelab.status import Outcome

TRIPLE = """[prusaslicer.base]
printer-profile = "Original Prusa i3 MK3S & MK3S+"
print-profile = "0.20mm QUALITY @MK3"
material-profile = "Prusament PLA"
"""

READBACK = "perimeters = 4\nlayer_height = 0.2\n"


@pytest.fixture
def intent(tmp_path: Path) -> Path:
    (tmp_path / "part.stl").write_text("solid cube\nendsolid cube\n", encoding="utf-8")
    path = tmp_path / "slice.toml"
    path.write_text(
        '[geometry]\nmodel = "part.stl"\n\n[output]\ngcode = "part.gcode"\n\n'
        + TRIPLE
        + "\n[prusaslicer.set]\nperimeters = 4\n",
        encoding="utf-8",
    )
    return path


@pytest.fixture
def engine_that_writes(monkeypatch: pytest.MonkeyPatch):
    """A stubbed engine that produces a good artifact and a matching configuration.

    Everything downstream of the run is real: the gate, the redaction, the diff, the
    container sniff and the promotion all see a file that is genuinely there.
    """
    form = LaunchForm(kind=LaunchKind.PATH, argv_prefix=["prusa-slicer"], description="stub")
    monkeypatch.setattr(
        slicing,
        "discover",
        lambda spec: Discovery(
            engine=spec.name, form=form, fidelity=ExitFidelity.ESTABLISHED, reason=""
        ),
    )
    monkeypatch.setattr(
        slicing, "configuration_state", lambda spec, found: slicing.ConfigState.PRESENT
    )
    mapped = MapEntry(
        keys=("perimeters",),
        side_effects=(),
        tracking=Tracking.EXACT,
        outcome=ProbeOutcome.MAPPED,
    )
    # `who` is accepted and ignored: the slice flow reads the identity once and hands
    # it to the real `_name_map` so the engine is not asked its version twice (#47).
    monkeypatch.setattr(slicing, "_name_map", lambda spec, found, who=None: {"perimeters": mapped})

    written: dict[str, Path] = {}

    def fake_run(argv, capture=()):
        # The staged paths are in the argv the adapter composed, which is also the
        # only place the engine would have found them.
        artifact = Path(argv[argv.index("-o") + 1])
        readback = Path(next(a for a in argv if a.startswith("--save=")).split("=", 1)[1])
        # The header has to match the engine's shape, because D9 now refuses an
        # artifact whose header slicelab cannot recognise -- and a stub that fails that
        # check was how the unimplemented rule stayed green in-tree.
        artifact.write_bytes(
            b"; generated by a slicer 1.0 on 2026-10-06 at 12:00:00 UTC\nG1 X0 Y0\n"
        )
        readback.write_text(READBACK, encoding="utf-8")
        written["artifact"] = artifact
        return Completed(exit_status=0, signal=None, stdout="", stderr="")

    monkeypatch.setattr(slicing, "run", fake_run)
    # The lock records the build it talked to, and `identify` asks the engine for its
    # version -- a third invocation in a `slice` run, after the slice and `--info`.
    # Stubbed here because this file's engine is a fabricated launch form: unstubbed it
    # tries to exec `prusa-slicer` off PATH and the failure reads as a broken test.
    monkeypatch.setattr(
        slicing,
        "identify",
        lambda spec, found: Identity(
            engine=spec.name,
            kind="path",
            version="9.9.9",
            banner=None,
            digest=None,
            digest_of=None,
        ),
    )
    return written


def _discard_if_kept() -> None:
    """Remove the scratch a withholding run kept, when the caller has no exception.

    The D9 refusal reaches the withheld-artifact path, so it keeps a scratch directory
    like any other withholding run -- measured, one per suite run. `tests/test_stray_files.py`
    cannot catch it: its subject is what the ENGINE leaves inside the scratch CWD, not
    slicelab's own directories outliving the run.
    """
    for directory in Path(tempfile.gettempdir()).glob("slicelab-slice-*"):
        shutil.rmtree(directory, ignore_errors=True)


def _discard(fault: BaseException) -> None:
    """Remove a scratch directory a test deliberately provoked slicelab into keeping.

    `tmp_path` does not reach it: it outlives the run by design (D7). Measured before
    this existed -- three directories left behind per suite run, which is the subject
    of `tests/test_stray_files.py` arriving from slicelab's own tests.
    """
    staged = withheld_by(fault)
    if staged is not None:
        shutil.rmtree(staged.parent, ignore_errors=True)


def test_a_clean_run_hands_over_and_leaves_no_scratch(intent: Path, engine_that_writes) -> None:
    """The control. Without it every test below passes on an implementation that
    keeps every scratch directory it ever makes."""
    done = slice_intent(intent)

    assert done.artifact == (intent.parent / "part.gcode").resolve()
    assert done.withheld is None
    assert not engine_that_writes["artifact"].exists(), "the scratch outlived a clean run"


def test_a_fault_after_a_good_artifact_keeps_it_and_names_it(
    intent: Path, engine_that_writes, monkeypatch: pytest.MonkeyPatch
) -> None:
    """`redact` refuses on an unmeasured secret key, which is a real refusal that
    happens after the engine has produced a perfectly good file.

    Before this, the artifact was deleted: the clause caught two exception classes
    and this is a third, so the `finally` ran with nothing kept and the author was
    told neither that a file had existed nor where it went.
    """
    monkeypatch.setattr(
        slicing,
        "redact",
        lambda text, spec: (_ for _ in ()).throw(RedactionError("no measurement")),
    )

    with pytest.raises(RedactionError) as raised:
        slice_intent(intent)

    staged = withheld_by(raised.value)
    assert staged is not None, "the artifact was destroyed by a fault it did not cause"
    assert staged.read_bytes().startswith(b"; generated by")
    _discard(raised.value)


def test_a_fault_from_an_unexpected_class_keeps_the_artifact(
    intent: Path, engine_that_writes, monkeypatch: pytest.MonkeyPatch
) -> None:
    """`sniff` opens a file with no guard, so an `OSError` here is not hypothetical.

    Named separately from the one above because they died for different reasons: that
    one was a class the clause did not list, this one is a class nobody would think
    to list. The rule is the fault's provenance, not its type.
    """
    monkeypatch.setattr(
        slicing, "sniff", lambda artifact, magic: (_ for _ in ()).throw(OSError("device is busy"))
    )

    with pytest.raises(OSError) as raised:
        slice_intent(intent)

    assert withheld_by(raised.value) is not None
    _discard(raised.value)


@pytest.mark.parametrize("payload", [None, b""], ids=["no file", "zero bytes"])
def test_a_run_that_produced_no_artifact_keeps_nothing_and_names_nothing(
    intent: Path, engine_that_writes, monkeypatch: pytest.MonkeyPatch, payload: bytes | None
) -> None:
    """[V4]'s shape. The report must not name a path, because there is no file at it
    -- and the scratch must go, because a directory kept per failed run that nobody
    is told about is litter rather than evidence.

    Twice, because the engine creates `-o` before it has anything to put in it, and a
    zero-byte file is the shape a run that failed immediately leaves. The gate and the
    withholding clause once disagreed on it: one report said the engine wrote no
    artifact and then named the empty one it had kept. With `is_file()` alone in the
    clause, the no-file case is green and the zero-byte case is exactly that report.
    """
    scratches: list[Path] = []

    def wrote_nothing(argv, capture=()):
        artifact = Path(argv[argv.index("-o") + 1])
        scratches.append(artifact.parent)
        if payload is not None:
            artifact.write_bytes(payload)
        return Completed(exit_status=0, signal=None, stdout="", stderr="outside the print volume")

    monkeypatch.setattr(slicing, "run", wrote_nothing)

    with pytest.raises(ResolveIncomplete) as raised:
        slice_intent(intent)

    assert withheld_by(raised.value) is None, "a report named an artifact that was never written"
    assert scratches, "the engine was never reached"
    assert not scratches[0].exists(), "a scratch directory nobody was told about survived"


@pytest.mark.skipif(os.name == "nt", reason="chmod cannot make a directory unwritable on Windows")
def test_a_failure_to_write_the_artifact_keeps_the_one_it_could_not_write(
    tmp_path: Path, engine_that_writes
) -> None:
    """Every destination knowably bad at plan time is refused there, so what reaches
    `promote` is a path that went wrong afterwards -- a directory that lost its write
    bit, a full filesystem, a race. The slice is still a good one, and making the
    author run it again to see it is the cost this clause exists to avoid.

    The output goes in a directory of its own. With everything in one directory the
    readback promotion failed first and this branch never ran, while the test passed
    on the exception raised one step earlier -- the assertion was true and about
    something else.
    """
    (tmp_path / "part.stl").write_text("solid cube\nendsolid cube\n", encoding="utf-8")
    (tmp_path / "out").mkdir()
    intent = tmp_path / "slice.toml"
    intent.write_text(
        '[geometry]\nmodel = "part.stl"\n\n[output]\ngcode = "out/part.gcode"\n\n'
        + TRIPLE
        + "\n[prusaslicer.set]\nperimeters = 4\n",
        encoding="utf-8",
    )
    (tmp_path / "out").chmod(0o500)
    try:
        with pytest.raises(ResolveError, match="cannot write the artifact") as raised:
            slice_intent(intent)
    finally:
        (tmp_path / "out").chmod(0o700)

    assert withheld_by(raised.value) is not None
    assert (tmp_path / "slice.readback.ini").is_file(), "the readback goes first (D31)"
    _discard(raised.value)


def test_a_readback_that_cannot_be_written_hands_over_nothing(
    tmp_path: Path, engine_that_writes
) -> None:
    """D31's ordering, which nothing pinned: moving `_promote_readback` after the
    artifact promotion left all 426 tests green.

    The readback destination is derived from the intent's name and is not one of the
    six things `plan_slice` refuses, so a directory standing there is reachable. With
    the readback second, this run exits 4 having already replaced the author's
    G-code -- which makes `slice`'s own "a non-zero means nothing was handed over"
    false in the case it most needs to be true.
    """
    (tmp_path / "part.stl").write_text("solid cube\nendsolid cube\n", encoding="utf-8")
    intent = tmp_path / "slice.toml"
    intent.write_text(
        '[geometry]\nmodel = "part.stl"\n\n[output]\ngcode = "part.gcode"\n\n'
        + TRIPLE
        + "\n[prusaslicer.set]\nperimeters = 4\n",
        encoding="utf-8",
    )
    (tmp_path / "part.gcode").write_text("PREVIOUS-ARTIFACT\n", encoding="utf-8")
    (tmp_path / "slice.readback.ini").mkdir()

    with pytest.raises(ResolveError) as raised:
        slice_intent(intent)

    assert (tmp_path / "part.gcode").read_text(encoding="utf-8") == "PREVIOUS-ARTIFACT\n", (
        "a run that exited non-zero had already handed over the artifact"
    )
    _discard(raised.value)


@pytest.mark.skipif(os.name == "nt", reason="chmod cannot make a file unwritable on Windows")
def test_a_lock_that_cannot_be_written_says_the_artifact_was_handed_over(
    intent: Path, engine_that_writes
) -> None:
    """The one place `slice` hands something over and still exits non-zero.

    The lock goes after the artifact because it describes where the artifact landed:
    written first, a failed promotion would leave a record asserting a file that is
    not there, and another tool reads the lock as its premise (D22). So the cost lands
    here instead, and the report has to carry it rather than claiming nothing moved.
    """
    destination = intent.parent / "slice.lock"
    destination.mkdir()

    with pytest.raises(ResolveError, match="the artifact was handed over") as raised:
        slice_intent(intent)

    assert "and the lock was not" in str(raised.value)
    assert (intent.parent / "part.gcode").is_file(), "the message says it was handed over"
    _discard(raised.value)


def test_a_fault_after_the_artifact_was_handed_over_does_not_claim_it_was_kept(
    intent: Path, engine_that_writes, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The report must not say "kept" about a file the author already has.

    Several faults are reachable after the promotion -- the lock write, and every
    filesystem read the lock builder makes. Setting the withheld path unconditionally
    made each of them report the opposite of what happened.
    """
    monkeypatch.setattr(
        slicing, "dumps", lambda document: (_ for _ in ()).throw(OSError("disk is full"))
    )

    with pytest.raises(Exception) as raised:
        slice_intent(intent)

    assert (intent.parent / "part.gcode").is_file(), "the artifact WAS handed over"
    assert withheld_by(raised.value) is None, "the report claimed the artifact was kept"
    _discard(raised.value)


def test_an_unrecognisable_header_is_incomplete_and_hands_over_nothing(
    intent: Path, engine_that_writes, monkeypatch: pytest.MonkeyPatch
) -> None:
    """D9, implemented rather than only described.

    A substitution count of 0 means the artifact is not in the format the comparison
    rule was measured against. The hash is withheld AND the run is `incomplete`, which
    with promote-on-sliced means nothing reaches the author -- the engine changing its
    header is when to stop, not when to ship a lock claiming less than a reader assumes.
    """
    previous = intent.parent / "part.gcode"
    previous.write_bytes(b"PREVIOUS\n")

    def unreadable_header(argv, capture=()):
        artifact = Path(argv[argv.index("-o") + 1])
        readback = Path(next(a for a in argv if a.startswith("--save=")).split("=", 1)[1])
        artifact.write_bytes(b"; sliced by something else entirely\nG1 X0\n")
        readback.write_text(READBACK, encoding="utf-8")
        return Completed(exit_status=0, signal=None, stdout="", stderr="")

    monkeypatch.setattr(slicing, "run", unreadable_header)

    with pytest.raises(ResolveIncomplete, match="header slicelab cannot recognise"):
        slice_intent(intent)

    assert previous.read_bytes() == b"PREVIOUS\n", "a good artifact reached the author"
    assert not (intent.parent / "slice.lock").exists()
    # D31: the readback is promoted on any outcome that was adjudicated at all, and this
    # run adjudicated. Refusing before the promotion left the author an `incomplete`
    # with nothing to check it against -- the exact failure D31 names.
    assert (intent.parent / "slice.readback.ini").is_file(), (
        "the verdict's own evidence was withheld because the verdict was bad"
    )
    _discard_if_kept()


def test_a_binary_container_is_not_refused_for_an_unrecognisable_header(
    intent: Path, engine_that_writes, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The control for the one above, and D10's boundary: normalization is never
    attempted on a container with no text footer, so it cannot fail there."""

    def binary_artifact(argv, capture=()):
        artifact = Path(argv[argv.index("-o") + 1])
        readback = Path(next(a for a in argv if a.startswith("--save=")).split("=", 1)[1])
        artifact.write_bytes(b"GCDE\x00\x01binary payload")
        readback.write_text(READBACK, encoding="utf-8")
        return Completed(exit_status=0, signal=None, stdout="", stderr="")

    monkeypatch.setattr(slicing, "run", binary_artifact)

    done = slice_intent(intent)

    assert done.outcome is Outcome.SLICED
    assert done.container is Container.BGCODE
    assert done.lock is not None


def test_a_run_that_hands_nothing_over_does_not_touch_the_lock(
    intent: Path, engine_that_writes, monkeypatch: pytest.MonkeyPatch
) -> None:
    """M1: dropping the `promoted is not None` guard left the whole suite green.

    A `coerced` run promotes nothing, so the lock beside it still describes the artifact
    that IS there. Removing it would discard a true record on every red run.
    """
    mapped = MapEntry(
        keys=("perimeters",), side_effects=(), tracking=Tracking.EXACT, outcome=ProbeOutcome.MAPPED
    )
    monkeypatch.setattr(slicing, "_name_map", lambda spec, found, who=None: {"perimeters": mapped})

    lock = intent.parent / "slice.lock"
    standing = 'schema_version = 1\n\n[artifact]\npath = "%s"\n' % (intent.parent / "part.gcode")
    lock.write_text(standing, encoding="utf-8")
    (intent.parent / "part.gcode").write_bytes(b"THE ARTIFACT THAT LOCK DESCRIBES\n")

    def coerced(argv, capture=()):
        artifact = Path(argv[argv.index("-o") + 1])
        readback = Path(next(a for a in argv if a.startswith("--save=")).split("=", 1)[1])
        artifact.write_bytes(b"; generated by a slicer 1.0 on 2026-10-06 at 12:00:00 UTC\nG1 X0\n")
        readback.write_text("perimeters = 9\n", encoding="utf-8")
        return Completed(exit_status=0, signal=None, stdout="", stderr="")

    monkeypatch.setattr(slicing, "run", coerced)

    done = slice_intent(intent)

    assert done.artifact is None, "nothing was handed over"
    assert done.stale_lock_removed is None
    assert lock.read_text(encoding="utf-8") == standing, "a non-promoting run removed the lock"
    _discard_if_kept()


def test_the_artifact_is_decoded_without_folding_bytes_together(
    intent: Path, engine_that_writes, monkeypatch: pytest.MonkeyPatch
) -> None:
    """M2: `_artifact_text` using `errors="replace"` left the whole suite green, because
    the digest test calls `normalized_sha256` with text it decoded itself.

    Two artifacts differing in one undecodable byte must not share a normalized hash, and
    this exercises the call site the fix changed rather than an adjacent one.
    """
    hashes = []
    for tail in (b"\xe9", b"\xff"):

        def wrote(argv, capture=(), tail=tail):
            artifact = Path(argv[argv.index("-o") + 1])
            readback = Path(next(a for a in argv if a.startswith("--save=")).split("=", 1)[1])
            artifact.write_bytes(
                b"; generated by a slicer 1.0 on 2026-10-06 at 12:00:00 UTC\nG1 X0 ; "
                + tail
                + b"\n"
            )
            readback.write_text(READBACK, encoding="utf-8")
            return Completed(exit_status=0, signal=None, stdout="", stderr="")

        monkeypatch.setattr(slicing, "run", wrote)
        done = slice_intent(intent)
        assert done.lock is not None
        hashes.append(
            tomllib.loads(done.lock.read_text(encoding="utf-8"))["artifact"]["normalized"]["sha256"]
        )

    assert hashes[0] != hashes[1], "two different artifacts share one normalized hash"


def test_the_inputs_are_hashed_before_the_engine_runs(
    intent: Path, engine_that_writes, monkeypatch: pytest.MonkeyPatch
) -> None:
    """M4 and M5: hashing the intent and the mesh after the run left the suite green.

    On a long slice an author's CAD re-export would be hashed instead of what was
    sliced. The stub rewrites both files while the engine is "running", so a hash taken
    afterwards records the new bytes.
    """
    before_intent = hashlib.sha256(intent.read_bytes()).hexdigest()
    before_mesh = hashlib.sha256((intent.parent / "part.stl").read_bytes()).hexdigest()
    inner = slicing.run

    def rewrites_its_inputs(argv, capture=()):
        completed = inner(argv, capture)
        intent.write_text(
            intent.read_text(encoding="utf-8") + "\n# edited mid-slice\n", encoding="utf-8"
        )
        (intent.parent / "part.stl").write_text("solid other\nendsolid other\n", encoding="utf-8")
        return completed

    monkeypatch.setattr(slicing, "run", rewrites_its_inputs)

    done = slice_intent(intent)
    document = tomllib.loads(done.lock.read_text(encoding="utf-8"))  # type: ignore[union-attr]

    assert document["intent"]["sha256"] == before_intent, "the intent was hashed after the run"
    assert document["geometry"]["mesh_sha256"] == before_mesh, "the mesh was hashed after the run"
    assert Path(document["intent"]["path"]).is_absolute(), "the intent path is unresolved"


def test_a_withheld_stat_points_at_the_value_not_the_table(
    intent: Path, engine_that_writes, monkeypatch: pytest.MonkeyPatch
) -> None:
    """M6: `stats.<field>` instead of `stats.<field>.value` left the suite green.

    The field itself is present, carrying the reason -- so naming it would make two of
    the schema's three absence cases identical on the wire.
    """

    def weightless(argv, capture=()):
        artifact = Path(argv[argv.index("-o") + 1])
        readback = Path(next(a for a in argv if a.startswith("--save=")).split("=", 1)[1])
        artifact.write_bytes(
            b"; generated by a slicer 1.0 on 2026-10-06 at 12:00:00 UTC\n"
            b"; filament used [mm] = 1251.87\n"
            b"; total filament used [g] = 0.00\n"
            b"; filament_density = 0\n"
        )
        readback.write_text(READBACK, encoding="utf-8")
        return Completed(exit_status=0, signal=None, stdout="", stderr="")

    monkeypatch.setattr(slicing, "run", weightless)

    done = slice_intent(intent)
    document = tomllib.loads(done.lock.read_text(encoding="utf-8"))  # type: ignore[union-attr]

    entry = next(e for e in document["unknowns"] if e["code"] == "filament_density_zero")
    assert entry["fields"] == ["stats.filament_g.value"], entry
    assert "filament_g" in document["stats"], "the field itself is present"
