"""The normalized hash means something only if something was normalized.

D9's rule is the whole value of the second hash: a substitution count of 0 says the
pattern matched nothing, so hashing the text anyway would publish the raw hash under
the normalized name -- a number that looks like evidence of reproducibility and is
evidence of nothing. The invariant here makes that unconstructable rather than
discouraged.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from slicelab.adapters.prusaslicer import _normalize_artifact
from slicelab.digest import HEADER_NOT_RECOGNISED, Normalized, normalized_sha256, raw_sha256

#: The engine's header shape, written here rather than copied. The timestamp is the
#: only part that varies: measured 2026-10-05, two slices of one cube differed in
#: exactly this line and nowhere else across 23422 lines.
HEADER = "; generated by PrusaSlicer 2.9.6 on 2026-10-05 at 19:47:33 UTC\n"
BODY = ";LAYER_CHANGE\nG1 X0 Y0 E1.0\n; filament used [mm] = 1251.87\n"


def test_a_normalized_hash_needs_a_substitution_to_have_happened() -> None:
    """0 substitutions and a digest is the raw hash wearing the normalized name."""
    with pytest.raises(ValueError, match="nothing was normalized"):
        Normalized(substitutions=0, sha256="a" * 64)


def test_a_normalized_result_is_a_digest_or_a_reason_and_never_both() -> None:
    with pytest.raises(ValueError, match="never both"):
        Normalized(substitutions=1, sha256="a" * 64, reason=HEADER_NOT_RECOGNISED)
    with pytest.raises(ValueError, match="never both"):
        Normalized(substitutions=1)


def test_the_timestamp_is_what_makes_two_runs_differ() -> None:
    """The same body under two timestamps normalizes to one hash."""
    first = normalized_sha256(HEADER + BODY, _normalize_artifact)
    second = normalized_sha256(HEADER.replace("19:47:33", "19:47:35") + BODY, _normalize_artifact)

    assert first.substitutions == 1
    assert first.sha256 == second.sha256
    assert first.reason is None


def test_a_different_build_still_changes_the_normalized_hash() -> None:
    """The version stays in the hash on purpose: a build that produces different
    toolpaths must not be reported as the same artifact."""
    mine = normalized_sha256(HEADER + BODY, _normalize_artifact)
    theirs = normalized_sha256(HEADER.replace("2.9.6", "2.9.7") + BODY, _normalize_artifact)
    assert mine.sha256 != theirs.sha256


def test_a_changed_toolpath_changes_the_normalized_hash() -> None:
    """The control for the two above. Normalization must not be so broad that it
    stops distinguishing artifacts, which is the failure mode of a normalizer."""
    mine = normalized_sha256(HEADER + BODY, _normalize_artifact)
    moved = normalized_sha256(HEADER + BODY.replace("G1 X0", "G1 X5"), _normalize_artifact)
    assert mine.sha256 != moved.sha256


@pytest.mark.parametrize(
    "header",
    [
        "; generated by SomeOtherSlicer 1.0\n",
        "; sliced on Tuesday\n",
        "",
        "; generated by PrusaSlicer 2.9.6 on 2026-10-05 at 19:47 UTC\n",
    ],
)
def test_an_unrecognised_header_withholds_the_hash(header: str) -> None:
    """Including a near miss: a timestamp without seconds is not the format the rule
    was measured against, and guessing at it is how a wrong hash gets published."""
    result = normalized_sha256(header + BODY, _normalize_artifact)
    assert result.sha256 is None
    assert result.substitutions == 0
    assert result.reason == HEADER_NOT_RECOGNISED
    assert "sha256" not in result.as_table()


def test_the_raw_hash_is_every_byte(tmp_path: Path) -> None:
    """Including the line the normalized hash removes, which is the point: one
    identifies the file and the other identifies the slice."""
    one = tmp_path / "one.gcode"
    one.write_text(HEADER + BODY, encoding="utf-8")
    two = tmp_path / "two.gcode"
    two.write_text(HEADER.replace("19:47:33", "19:47:35") + BODY, encoding="utf-8")

    assert len(raw_sha256(one)) == 64
    assert raw_sha256(one) != raw_sha256(two), "the raw hash must see the timestamp"
    assert (
        normalized_sha256(one.read_text(encoding="utf-8"), _normalize_artifact).sha256
        == normalized_sha256(two.read_text(encoding="utf-8"), _normalize_artifact).sha256
    )
