"""PrusaSlicer."""

from __future__ import annotations

from collections.abc import Mapping

from slicelab.adapters.base import EngineSpec, OptionProbe, PresetQuery


def _options_from_help_fff(help_text: str, baseline: Mapping[str, str]) -> tuple[str, ...]:
    """Every option spelling `--help-fff` lists, aliases included.

    ``baseline`` is unused: PrusaSlicer states its own option list, so the
    candidates do not have to be inferred from the keys.

    **Aliases are collected, and that is the point of reading past the first
    name on a line.** D28 records the cost of not doing so: a scan that reads
    only the leading option sees 411 names, misses that ``--after-layer-gcode
    ABCD, --layer-gcode ABCD`` is one line offering two spellings, and then
    manufactures orphan config keys by set-subtracting the two populations. An
    alias is also where G2's worst case lives -- a spelling whose underscore
    form is some *other* real key would compare against the wrong key and could
    report ``applied`` on an unhonoured intent -- so a search for that collision
    is only exhaustive over a list that has the aliases in it.

    Each option line begins with a space and two dashes, and carries
    comma-separated spellings before the description; a spelling may be followed
    by a metavar (``ABCD``, ``N``, ``X,Y``). Reading stops at the first
    comma-separated group that does not begin with a dash, which is the
    description.
    """
    del baseline
    found: list[str] = []
    for line in help_text.splitlines():
        if not line.startswith(" --"):
            continue
        for group in line.strip().split(", "):
            if not group.startswith("-"):
                break
            name = group.split()[0]
            if name.startswith("--") and len(name) > 2:
                found.append(name[2:])
    return tuple(dict.fromkeys(found))


def _read_ini(text: str) -> Mapping[str, str]:
    """A PrusaSlicer `--save` dump as key/value pairs.

    Not `configparser`: the dump has a section-less preamble of `# generated by`
    comments, and values are taken verbatim because a resolved G-code block or a
    bracket template must survive the round trip unaltered.
    """
    out: dict[str, str] = {}
    for line in text.splitlines():
        if line.startswith("#") or line.startswith("["):
            continue
        key, separator, value = line.partition(" = ")
        if separator:
            out[key.strip()] = value
    return out


#: Ordered by how distinctive the result is. Measured against 2.9.6: a string
#: marker lands unambiguously where it is accepted, and the numeric forms follow
#: for the typed options that reject it at rc=1.
_SENTINELS = ("SLICELABPROBE", "7", "0.17", "37%", "1", "3x4", "0x0,7x0,7x7,0x7", "0.37,0.37")

PROBE = OptionProbe(
    sentinels=_SENTINELS,
    # 2.9.6 answers `Unknown option --foo` on stderr at rc=1. A wrong *value* for
    # a real option answers `Invalid value supplied` instead, so the two cases are
    # distinguishable and only the second is worth another sentinel.
    unknown_option="unknown option",
    candidates=_options_from_help_fff,
    read_config=_read_ini,
    enumerate_argv=("--help-fff",),
)

SPEC = EngineSpec(
    name="prusaslicer",
    # The console variant is the one that speaks on Windows; the GUI binary
    # detaches and answers nothing.
    posix_exec="prusa-slicer",
    windows_exec="prusa-slicer-console.exe",
    flatpak_app_id="com.prusa3d.PrusaSlicer",
    # The Homebrew cask installs /Applications/PrusaSlicer.app; the binary in
    # its Contents/MacOS carries the application's name.
    macos_exec=("PrusaSlicer", "prusa-slicer"),
    # Exits 1 on complete success, with valid JSON on stdout and nothing on
    # stderr -- the same code it returns for "that printer was not found"
    # (notes/evidence.md V5). slicelab adjudicates the artifact, never this
    # exit code (D17).
    readback_flag="--save",
    # Measured 2026-09-10 across seven boolean options. `1` and `0` are the only two
    # spellings that mean the same thing everywhere: =1 resolved true and =0 resolved
    # false on every option tried, both directions. EVERYTHING ELSE is per-option.
    # --spiral-vase=True resolves to 0; --thin-walls=False resolves to 1, the literal
    # string "False" turning the option ON; --cooling=True yields an empty value that
    # is neither. All at exit 0 with zero stderr, because boolean options validate
    # nothing. The hazard is bidirectional, so the only safe emission is one of the
    # two words every option agreed on.
    bool_words=("1", "0"),
    base_keys=("printer-profile", "print-profile", "material-profile"),
    preset_query=PresetQuery(argv=("--query-printer-models",), root_key="printer_models"),
    option_probe=PROBE,
)
