"""PrusaSlicer."""

from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path

from slicelab.adapters.base import ConfigLocation, EngineSpec, Invocation, OptionProbe, PresetQuery
from slicelab.redact import REDACTED


def _options_from_help_fff(help_text: str, baseline: Mapping[str, str]) -> tuple[str, ...]:
    """Every option spelling `--help-fff` lists, aliases included.

    ``baseline`` is unused: PrusaSlicer states its own option list, so the
    candidates do not have to be inferred from the keys.

    **Aliases are collected, and that is the point of reading past the first
    name on a line.** D28 records the cost of not doing so: a scan that reads
    only the leading option sees 411 names, misses that ``--after-layer-gcode
    ABCD, --layer-gcode ABCD`` is one line offering two spellings, and then
    manufactures orphan config keys by set-subtracting the two populations. An
    alias is also where G2's worst case lives -- a spelling whose underscore
    form is some *other* real key would compare against the wrong key and could
    report ``applied`` on an unhonoured intent -- so a search for that collision
    is only exhaustive over a list that has the aliases in it.

    Each option line begins with a space and two dashes, and carries
    comma-separated spellings before the description; a spelling may be followed
    by a metavar (``ABCD``, ``N``, ``X,Y``). Reading stops at the first
    comma-separated group that does not begin with a dash, which is the
    description.
    """
    del baseline
    found: list[str] = []
    for line in help_text.splitlines():
        if not line.startswith(" --"):
            continue
        for group in line.strip().split(", "):
            if not group.startswith("-"):
                break
            name = group.split()[0]
            if name.startswith("--") and len(name) > 2:
                found.append(name[2:])
    return tuple(dict.fromkeys(found))


def _redact_ini(text: str, secret_keys: tuple[str, ...]) -> str:
    """Replace the values of `secret_keys`, leaving every other byte alone.

    Line-based, so the promoted sidecar is the engine's own bytes apart from the
    named values -- same lines, same order, same spacing, `# generated by` header
    included. That matters because the sidecar is evidence: a reformatted one would
    be slicelab's rendering of the engine's answer rather than the answer.

    Lived in `redact.py` until OrcaSlicer's JSON was handed to it, which it silently
    left untouched. The core keeps the policy and the check; this is only the part
    that knows what an ini line looks like.
    """
    wanted = set(secret_keys)
    lines = text.splitlines(keepends=True)
    for index, line in enumerate(lines):
        key, separator, _ = line.partition(" = ")
        if not separator or key.strip() not in wanted:
            continue
        ending = line[len(line.rstrip("\r\n")) :]
        lines[index] = f"{key}{separator}{REDACTED}{ending}"
    return "".join(lines)


def _read_ini(text: str) -> Mapping[str, str]:
    """A PrusaSlicer `--save` dump as key/value pairs.

    Not `configparser`: the dump has a section-less preamble of `# generated by`
    comments, and values are taken verbatim because a resolved G-code block or a
    bracket template must survive the round trip unaltered.
    """
    out: dict[str, str] = {}
    for line in text.splitlines():
        if line.startswith("#") or line.startswith("["):
            continue
        key, separator, value = line.partition(" = ")
        if separator:
            out[key.strip()] = value
    return out


#: Pairs, ordered by how distinctive the result is: a string marker lands
#: unambiguously where it is accepted, and the numeric forms follow for the typed
#: options that reject it at rc=1.
#:
#: The percent pair earns its place twice over. `--fill-density` is a *fraction*
#: when given bare, so `=7` and `=40` are refused at rc=1 with `Value out of
#: range: fill_density` and no ini written -- loud, named, and handled by the
#: cascade rather than read as "moved nothing", because D7's artifact gate is
#: what tells a failed run from an empty answer. `=0.17` is accepted and resolves
#: to `17%`, which responds to the value but does not carry it, so the float pair
#: yields only an inexact entry; `=37%` tracks exactly. That is why the cascade
#: keeps looking after an inexact result rather than settling for it.
_SENTINELS = (
    ("SLICELABPROBE", "SLICELABOTHER"),
    ("7", "3"),
    ("0.17", "0.29"),
    ("37%", "61%"),
    ("1", "0"),
    ("3x4", "5x6"),
    ("0x0,7x0,7x7,0x7", "0x0,9x0,9x9,0x9"),
    ("0.37,0.37", "0.53,0.53"),
)


def _ask_for_a_slice(model: Path, artifact: Path, readback: Path) -> Invocation:
    """Slice this model, write the G-code there, and dump the configuration beside it.

    **One invocation, not two.** The configuration has to come from the run that
    produced the artifact or it is a document about a different run -- and 2.9.6 makes
    that concrete: `--save` executes BEFORE the slice block and is not conditioned on
    it, so a run that slices nothing still writes a complete config at rc=0 [V4]. The
    gate that catches it lives in `slice`; composing the two together is what gives
    the gate something to compare.

    **The model is the author's own path, never a copy.** Its basename is embedded in
    `objects_info` whenever `gcode_label_objects` is `firmware` or `octoprint`, which
    Prusa's shipped presets set -- measured here, a cube sliced from `cube.stl` carries
    `"name":"cube.stl id:0 copy 0"`. Slicing a renamed temp copy would put slicelab's
    scratch filename inside the artifact the author keeps (D7).
    """
    # SPACE-SEPARATED, both of them, and `--save` with `=`. Measured on 2.9.6, and
    # not guessable: `--export-gcode=<model> -o=<path>` is accepted, exits **0**,
    # writes a complete 14757-byte configuration and **no G-code at all**. So is
    # `--export-gcode=<model> -o <path>`. Each is [V4]'s exact shape -- rc=0 with a
    # config and no artifact -- produced by an argv bug rather than by a bad request,
    # which is the strongest argument for the gate there is: slicelab's own mistake
    # looks identical to the engine's.
    return Invocation(
        argv=("--export-gcode", str(model), "-o", str(artifact), f"--save={readback}"),
        paths=frozenset({str(model), str(artifact), str(readback)}),
    )


PROBE = OptionProbe(
    sentinels=_SENTINELS,
    # 2.9.6 answers `Unknown option --foo` on stderr at rc=1. A wrong *value* for
    # a real option answers `Invalid value supplied` instead, so the two cases are
    # distinguishable and only the second is worth another sentinel.
    unknown_option="unknown option",
    candidates=_options_from_help_fff,
    enumerate_argv=("--help-fff",),
)

SPEC = EngineSpec(
    name="prusaslicer",
    # The console variant is the one that speaks on Windows; the GUI binary
    # detaches and answers nothing.
    posix_exec="prusa-slicer",
    windows_exec="prusa-slicer-console.exe",
    flatpak_app_id="com.prusa3d.PrusaSlicer",
    # The Homebrew cask installs /Applications/PrusaSlicer.app; the binary in
    # its Contents/MacOS carries the application's name.
    macos_exec=("PrusaSlicer", "prusa-slicer"),
    # Exits 1 on complete success, with valid JSON on stdout and nothing on
    # stderr -- the same code it returns for "that printer was not found"
    # (notes/evidence.md V5). slicelab adjudicates the artifact, never this
    # exit code (D17).
    # Measured 2026-09-11 by ENUMERATING the family rather than sampling a default
    # dump, which is how the first three came to be the only three. The binary
    # carries twelve `print_host*` / `printhost_*` names; each was set to a marker
    # via `--load`, alongside a preset triple and `--save`, and the dump inspected:
    #
    #   emitted, carrying the value that was set  -> a credential, listed here
    #     print_host  printhost_apikey  printhost_cafile
    #     printhost_password  printhost_port  printhost_user
    #   emitted, coerced to a fixed value         -> carries nothing authored
    #     printhost_authorization_type (-> 'key')  printhost_ssl_ignore_revoke (-> '0')
    #   not emitted at all
    #     print_host_webui  printhost_group  printhost_path  printhost_storage
    #
    # Control, in the same run: a fabricated key was dropped from the dump [V2], so
    # "emitted" means a real key of the saved namespace and not an echo of --load.
    #
    # The first three were measured against a dump that structurally could not
    # contain the others -- a default preset sets no digest credentials, so nothing
    # was there to find. `readback.py` states the hazard ("the readback's key SET is
    # value-dependent"); the credential measurement was the thing it happened to.
    # `test_credentials_are_enumerated_not_sampled` keeps this honest, and its
    # population comes from the BUILD rather than from a list anyone maintains: it
    # reads credential-shaped names out of the binary's string table (118 on 2.9.6),
    # sets each to a marker, and then rules on every credential-shaped key in the
    # resulting dump. A hand-written tuple was the first attempt and it was the same
    # sampling error one level up -- a name nobody listed is never set, never
    # appears, and no check downstream can see it.
    #
    # The remaining limit, stated rather than implied: a credential whose NAME reads
    # like nothing in `CREDENTIAL_NAME_WORDS`. `--help-fff` cannot close it either --
    # 416 option spellings and not one of these names among them. (416, not the 411
    # this module's own docstring names: 411 is the leading-position scan, which
    # misses aliases. `_options_from_help_fff` returns 416 and that is the set that
    # was checked.)
    secret_keys=(
        "print_host",
        "printhost_apikey",
        "printhost_cafile",
        "printhost_password",
        "printhost_port",
        "printhost_user",
    ),
    # Measured on this host: the Flatpak keeps configuration at
    # ~/.var/app/com.prusa3d.PrusaSlicer/config/PrusaSlicer/, and `PrusaSlicer.ini` is
    # written there once the engine has been configured. The directory itself is not
    # the question -- the Flatpak runtime creates one before the engine has ever run.
    #
    # Only the Flatpak path is declared, because only the Flatpak is installed here.
    # The others are left `None` deliberately: slicelab would be asserting a location
    # nobody checked, and `configured.py` treats an undeclared platform as "could not
    # tell" rather than "not configured". Filling them in is a measurement, not a
    # lookup, and belongs to whoever has that install (#19).
    config_location=ConfigLocation(marker="PrusaSlicer.ini", flatpak="PrusaSlicer"),
    readback_flag="--save",
    # Measured 2026-09-10 across seven boolean options. `1` and `0` are the only two
    # spellings that mean the same thing everywhere: =1 resolved true and =0 resolved
    # false on every option tried, both directions. EVERYTHING ELSE is per-option.
    # --spiral-vase=True resolves to 0; --thin-walls=False resolves to 1, the literal
    # string "False" turning the option ON; --cooling=True yields an empty value that
    # is neither. All at exit 0 with zero stderr, because boolean options validate
    # nothing. The hazard is bidirectional, so the only safe emission is one of the
    # two words every option agreed on.
    bool_words=("1", "0"),
    base_keys=("printer-profile", "print-profile", "material-profile"),
    # No `compose_base`: this engine addresses presets BY NAME, one flag per key,
    # which is what the core composes by default. Orca is the one that needed a seam.
    # `binary_gcode = 1` is the stock default for the entire current Prusa line, so
    # this is the ordinary path rather than an edge case [V7]. Measured on 2.9.6: a
    # cube sliced with `--binary-gcode=1` is 135019 bytes beginning `GCDE`, with zero
    # `prusaslicer_config` markers; the same cube as text is 604407 bytes beginning
    # `; ge`, with two.
    binary_container_magic=b"GCDE",
    compose_slice=_ask_for_a_slice,
    read_readback=_read_ini,
    redact_readback=_redact_ini,
    preset_query=PresetQuery(argv=("--query-printer-models",), root_key="printer_models"),
    option_probe=PROBE,
)
